### ISSUE TITLE
ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by Primtek** [Microsoft/BotFramework-WebChat#1126]
try to run botchat.js but facing the following 
I m stuck .. any body please help me?

===

[root@ai BotFramework-WebChat-master]# node botchat.js
/home/primtek/BotFramework-WebChat-master/botchat.js:23114
var IS_FIREFOX = /Firefox\//i.test(navigator.userAgent);
                                  ^

ReferenceError: navigator is not defined
    at Object.<anonymous> (/home/primtek/BotFramework-WebChat-master/botchat.js:23114:36)
    at __webpack_require__ (/home/primtek/BotFramework-WebChat-master/botchat.js:30:30)
    at Object.<anonymous> (/home/primtek/BotFramework-WebChat-master/botchat.js:3854:21)
    at __webpack_require__ (/home/primtek/BotFramework-WebChat-master/botchat.js:30:30)
    at Object.defineProperty.value (/home/primtek/BotFramework-WebChat-master/botchat.js:17841:14)
    at __webpack_require__ (/home/primtek/BotFramework-WebChat-master/botchat.js:30:30)
    at Object.defineProperty.value (/home/primtek/BotFramework-WebChat-master/botchat.js:21910:13)
    at __webpack_require__ (/home/primtek/BotFramework-WebChat-master/botchat.js:30:30)
    at module.exports (/home/primtek/BotFramework-WebChat-master/botchat.js:76:18)
    at /home/primtek/BotFramework-WebChat-master/botchat.js:79:10
[root@ai BotFramework-WebChat-master]#

**Comment by Kartik1607** [comment]
Hi,
which Firefox version are you using? It looks like window.

Adding `const navigator = window.navigator || <any>{};` [here](https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/getTabIndex.ts#L2) would fix the issue.

**Comment by compulim** [comment]
Close due to inactivity.
