### ISSUE TITLE
styleSet is not defined

### ISSUE THREAD

**Issue by Kartik1607** [Microsoft/BotFramework-WebChat#1274]
Was going through samples and ran [Full-featured e5 bundle](https://microsoft.github.io/BotFramework-WebChat/es5-bundle/) sample. 
Using `show animation, audio, video ` (content-multimedia) produces error.

```
ReferenceError: styleSet is not defined
    at botchat-es5.js:43
    at botchat-es5.js:59
    at eo (botchat-es5.js:59)
    at Po (botchat-es5.js:59)
    at jo (botchat-es5.js:59)
    at fa (botchat-es5.js:59)
    at la (botchat-es5.js:59)
    at Ro (botchat-es5.js:59)
    at Object.enqueueSetState (botchat-es5.js:59)
    at a._.setState (botchat-es5.js:37)
oo @ botchat-es5.js:59
botchat-es5.js:1 uncaught at e ReferenceError: styleSet is not defined
    at https://cdn.botframework.com/botframework-webchat/preview/botchat-es5.js:43:19683
    at https://cdn.botframework.com/botframework-webchat/preview/botchat-es5.js:59:59700
    at eo (https://cdn.botframework.com/botframework-webchat/preview/botchat-es5.js:59:60102)
    at Po (https://cdn.botframework.com/botframework-webchat/preview/botchat-es5.js:59:74313)
    at jo (https://cdn.botframework.com/botframework-webchat/preview/botchat-es5.js:59:74659)
    at fa (https://cdn.botframework.com/botframework-webchat/preview/botchat-es5.js:59:79327)
    at la (https://cdn.botframework.com/botframework-webchat/preview/botchat-es5.js:59:78981)
    at Ro (https://cdn.botframework.com/botframework-webchat/preview/botchat-es5.js:59:77493)
    at Object.enqueueSetState (https://cdn.botframework.com/botframework-webchat/preview/botchat-es5.js:59:46428)
    at a._.setState (https://cdn.botframework.com/botframework-webchat/preview/botchat-es5.js:37:1281)
```

Haven't looked into source code yet to figure out root issue.

**Comment by compulim** [comment]
Thanks for catching the last-minute bug. Will be fixed in #1260.
