### ISSUE TITLE
Test reliability: `basic.js` "Absolute timestamp" test is timing out

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2716]
## Feature Request

We are seeing the `basic.js` "absolute timestamp" test is causing a timeout.

```
FAIL __tests__/basic.js (174.676s)
  ● absolute timestamp

    : Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.Error:

      146 | });
      147 | 
    > 148 | test('absolute timestamp', async () => {
          | ^
      149 |   const activities = [
      150 |     {
      151 |       type: 'message',

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Object.<anonymous> (__tests__/basic.js:148:1)

  ● absolute timestamp

    TimeoutError: Waiting Direct Line to connect
    Wait timed out after 15209ms

      at node_modules/selenium-webdriver/lib/webdriver.js:841:17

  ● absolute timestamp

    TimeoutError: Waiting Direct Line to connect
    Wait timed out after 15209ms

      at node_modules/selenium-webdriver/lib/webdriver.js:841:17

  ● avatar background color

    TimeoutError: Waiting Direct Line to connect
    Wait timed out after 15209ms

      at node_modules/selenium-webdriver/lib/webdriver.js:841:17

  ● avatar background color

    TimeoutError: Waiting Direct Line to connect
    Wait timed out after 15209ms

      at node_modules/selenium-webdriver/lib/webdriver.js:841:17
```

[Enhancement]

**Comment by compulim** [comment]
Fake negative.
