### ISSUE TITLE
SecurityError in Internet Explorer

### ISSUE THREAD

**Issue by dkonyayev** [microsoft/BotFramework-WebChat#2775]
I am getting a SecurityError in my code when running in IE11. This works fine for Chrome. I am attaching the sample HTML code. Just replace <token> with valid DirectLine token and try it in IE11.

## Error Messages
Invoking bot application with userId: 5b33e99a-a8f6-4cbf-936f-c7f798730d76
Domain: tools
SCRIPT5022: SecurityError
webchat-es5.js (1,110795)
uncaught at anonymous SecurityError
uncaught at anonymous TypeError: Unable to get property 'error' of undefined or null reference
   at t.default (https://cdn.botframework.com/botframework-webchat/latest/webchat-es5.js:1:494105)
   at Anonymous function (https://cdn.botframework.com/botframework-webchat/latest/webchat-es5.js:1:287069)
   at m (https://cdn.botframework.com/botframework-webchat/latest/webchat-es5.js:1:285111)
   at Anonymous function (https://cdn.botframework.com/botframework-webchat/latest/webchat-es5.js:1:1341082)
   at Anonymous function (http://localhost:3978/directlinechat.htm?d=tools:152:33)
   at i.dispatch (https://cdn.botframework.com/botframework-webchat/latest/webchat-es5.js:1:288329)
   at Anonymous function (https://cdn.botframework.com/botframework-webchat/latest/webchat-es5.js:1:5845)
   at Anonymous function (https://cdn.botframework.com/botframework-webchat/latest/webchat-es5.js:1:1335784)
   at o (https://cdn.botframework.com/botframework-webchat/latest/webchat-es5.js:1:134369)
   at c (https://cdn.botframework

## Sample code
[webchat-code.txt](https://github.com/microsoft/BotFramework-WebChat/files/4000843/webchat-code.txt)

**Comment by dkonyayev** [comment]
Restarted IE and issue went away.

**Comment by Junlol** [comment]
This problem sometimes happens.

**Comment by narik1989** [comment]
Hi,

This happens always. I have integrated chat bot in my application. The application is running in IE. When i logout and login in the application the webchat-es5.js always shows security error. I am using version 4.6.0. Is there any resolution for this?

Thanks
Kiran
