### ISSUE TITLE
Test reliability chores

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2938]
### `chrome.dockerfile`

```dockerfile
FROM selenium/node-chrome:4.0.0-beta-3-20210426

ADD __tests__/setup/local ~/Downloads
```

### `docker-compose-wsl2.yml`

```dockerfile
  chrome:
    build:
      context: ./
      dockerfile: chrome.dockerfile
    depends_on:
      - selenium-hub
      - webchat
      - webchat2
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: '4442'
      SE_EVENT_BUS_SUBSCRIBE_PORT: '4443'
      SE_OPTS: '--log-level WARNING'

  selenium-hub:
    image: selenium/hub:4.0.0-beta-3-20210426
    container_name: selenium-hub
    environment:
      GRID_TIMEOUT: '300'
    ports:
      - '4444:4444'
```

### `__tests__/html/newMessageButton.tabOrder.js`

```
Error: Timed out while waiting for page condition "New message button is shown" after 1 seconds.
See screenshot for details: /tmp/newMessageButton.tabOrder.png
Error: Timed out while waiting for page condition "New message button is shown" after 1 seconds.
at became (http://webchat2/test-page-object.js:15690:11)
at async http://webchat2/tests/html/newMessageButton.tabOrder:52:9
```

<details>
<summary>Click to show screenshot</summary>

![image](https://user-images.githubusercontent.com/1622400/118035669-5fa66d80-b320-11eb-8b1c-00dd40b10a64.png)

</details>

### `__tests__/html/carousel.navigation.tab.cardInput.js`

```
Error: Timed out while waiting for page condition "focused activity scroll into view" after 5 seconds.
See screenshot for details: /tmp/carousel.navigation.tab.cardInput.png
Error: Timed out while waiting for page condition "focused activity scroll into view" after 5 seconds.
at became (http://webchat2/test-page-object.js:15690:11)
at async Object.focusedActivityInView (http://webchat2/test-page-object.js:18984:5)
at async http://webchat2/tests/html/carousel.navigation.tab.cardInput:31:9
```

<details>
<summary>Click to show screenshot</summary>

![image](https://user-images.githubusercontent.com/1622400/118035794-8cf31b80-b320-11eb-8ff2-77984fb26657.png)

</details>

### `__tests__/html/transcript.navigation.escapeKey.js`

```
Error: Timed out while waiting for page condition "focused activity scroll into view" after 5 seconds.
See screenshot for details: /tmp/transcript.navigation.escapeKey.png
Error: Timed out while waiting for page condition "focused activity scroll into view" after 5 seconds.
at became (http://webchat2/test-page-object.js:15690:11)
at async Object.focusedActivityInView (http://webchat2/test-page-object.js:18984:5)
at async http://webchat2/tests/html/transcript.navigation.escapeKey:39:9
```

<details>
<summary>Click to show screenshot</summary>

![image](https://user-images.githubusercontent.com/1622400/118035868-a98f5380-b320-11eb-97c1-6f972eb48eae.png)

</details>

### `__tests__/html/hooks.useTextBox.js`

```
Expected image to match or be a close match to snapshot but was 5.200520833333333% different from snapshot (11982 differing pixels).
See diff for details: /home/vsts/work/1/s/tests/image_snapshots/html/diff_output/hooks-use-text-box-js-use-text-box-should-work-properly-1-diff.png
See screenshot for details: /tmp/hooks.useTextBox.png
```

<details>
<summary>Click to expand stack trace</summary>

```
Error: Failed: Object {
"matcherResult": Object {
"message": "() => {
let failure;
if (result.diffSize && !allowSizeMismatch) {
failure = Expected image to be the same size as the snapshot (${result.imageDimensions.baselineWidth}x${result.imageDimensions.baselineHeight}), but was different (${result.imageDimensions.receivedWidth}x${result.imageDimensions.receivedHeight}).\\n;
} else {
failure = Expected image to match or be a close match to snapshot but was ${differencePercentage}% different from snapshot (${result.diffPixelCount} differing pixels).\\n;
}

    failure += `${chalk.bold.red('See diff for details:')} ${chalk.red(result.diffOutputPath)}`;

    const supportedInlineTerms = [
      'iTerm.app',
      'WezTerm',
    ];

    if (dumpInlineDiffToConsole && (supportedInlineTerms.includes(process.env.TERM_PROGRAM) || 'ENABLE_INLINE_DIFF' in process.env)) {
      failure += `\\n\\n\\t\\x1b]1337;File=name=${Buffer.from(result.diffOutputPath).toString('base64')};inline=1;width=40:${result.imgSrcString.replace('data:image/png;base64,', '')}\\x07\\x1b\\n\\n`;
    } else if (dumpDiffToConsole || dumpInlineDiffToConsole) {
      failure += `\\n${chalk.bold.red('Or paste below image diff string to your browser`s URL bar.')}\\n ${result.imgSrcString}`;
    }

    return failure;
  }",
"pass": false,
},
"message": "Expected image to match or be a close match to snapshot but was 5.200520833333333% different from snapshot (11982 differing pixels).
See diff for details: /home/vsts/work/1/s/tests/image_snapshots/html/diff_output/hooks-use-text-box-js-use-text-box-should-work-properly-1-diff.png
See screenshot for details: /tmp/hooks.useTextBox.png
",
}
at Env.it (/home/vsts/work/1/s/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:95:24)
at it (/home/vsts/work/1/s/node_modules/jest-jasmine2/build/jasmine/jasmineLight.js:100:21)
at Suite.<anonymous> (/home/vsts/work/1/s/tests/html/hooks.useTextBox.js:4:3)
at addSpecsToSuite (/home/vsts/work/1/s/node_modules/jest-jasmine2/build/jasmine/Env.js:444:51)
at Env.describe (/home/vsts/work/1/s/node_modules/jest-jasmine2/build/jasmine/Env.js:414:11)
at describe (/home/vsts/work/1/s/node_modules/jest-jasmine2/build/jasmine/jasmineLight.js:88:18)
at Object.<anonymous> (/home/vsts/work/1/s/tests/html/hooks.useTextBox.js:3:1)
at Runtime._execModule (/home/vsts/work/1/s/node_modules/jest-runtime/build/index.js:1299:24)
at Runtime._loadModule (/home/vsts/work/1/s/node_modules/jest-runtime/build/index.js:898:12)
at Runtime.requireModule (/home/vsts/work/1/s/node_modules/jest-runtime/build/index.js:746:10)
```

</details>

<details>
<summary>Click to show screenshots</summary>

![image](https://user-images.githubusercontent.com/1622400/118036134-0a1e9080-b321-11eb-8580-ee4fb2fdaefc.png)

![image](https://user-images.githubusercontent.com/1622400/118036143-0db21780-b321-11eb-854c-5d78f98dbffa.png)

</details>

### `__tests__/html/focusManagement.newMessageButton.receiveHeroCard.js` › focus management after receive hero card, click on new message button should focus on button

```
Expected image to match or be a close match to snapshot but was 13.20529513888889% different from snapshot (30425 differing pixels).
See diff for details: /home/vsts/work/1/s/tests/image_snapshots/html/diff_output/focus-management-new-message-button-receive-hero-card-js-focus-management-after-receive-hero-card-click-on-new-message-button-should-focus-on-button-1-diff.png
See screenshot for details: /tmp/focusManagement.newMessageButton.receiveHeroCard.png
```

<details>
<summary>Click to expand stack trace</summary>

```
Error: Failed: Object {
"matcherResult": Object {
"message": "() => {
let failure;
if (result.diffSize && !allowSizeMismatch) {
failure = Expected image to be the same size as the snapshot (${result.imageDimensions.baselineWidth}x${result.imageDimensions.baselineHeight}), but was different (${result.imageDimensions.receivedWidth}x${result.imageDimensions.receivedHeight}).\\n;
} else {
failure = Expected image to match or be a close match to snapshot but was ${differencePercentage}% different from snapshot (${result.diffPixelCount} differing pixels).\\n;
}

    failure += `${chalk.bold.red('See diff for details:')} ${chalk.red(result.diffOutputPath)}`;

    const supportedInlineTerms = [
      'iTerm.app',
      'WezTerm',
    ];

    if (dumpInlineDiffToConsole && (supportedInlineTerms.includes(process.env.TERM_PROGRAM) || 'ENABLE_INLINE_DIFF' in process.env)) {
      failure += `\\n\\n\\t\\x1b]1337;File=name=${Buffer.from(result.diffOutputPath).toString('base64')};inline=1;width=40:${result.imgSrcString.replace('data:image/png;base64,', '')}\\x07\\x1b\\n\\n`;
    } else if (dumpDiffToConsole || dumpInlineDiffToConsole) {
      failure += `\\n${chalk.bold.red('Or paste below image diff string to your browser`s URL bar.')}\\n ${result.imgSrcString}`;
    }

    return failure;
  }",
"pass": false,
},
"message": "Expected image to match or be a close match to snapshot but was 13.20529513888889% different from snapshot (30425 differing pixels).
See diff for details: /home/vsts/work/1/s/tests/image_snapshots/html/diff_output/focus-management-new-message-button-receive-hero-card-js-focus-management-after-receive-hero-card-click-on-new-message-button-should-focus-on-button-1-diff.png
See screenshot for details: /tmp/focusManagement.newMessageButton.receiveHeroCard.png
",
}
at Env.it (/home/vsts/work/1/s/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:95:24)
at it (/home/vsts/work/1/s/node_modules/jest-jasmine2/build/jasmine/jasmineLight.js:100:21)
at Suite.<anonymous> (/home/vsts/work/1/s/tests/html/focusManagement.newMessageButton.receiveHeroCard.js:4:3)
at addSpecsToSuite (/home/vsts/work/1/s/node_modules/jest-jasmine2/build/jasmine/Env.js:444:51)
at Env.describe (/home/vsts/work/1/s/node_modules/jest-jasmine2/build/jasmine/Env.js:414:11)
at describe (/home/vsts/work/1/s/node_modules/jest-jasmine2/build/jasmine/jasmineLight.js:88:18)
at Object.<anonymous> (/home/vsts/work/1/s/tests/html/focusManagement.newMessageButton.receiveHeroCard.js:3:1)
at Runtime._execModule (/home/vsts/work/1/s/node_modules/jest-runtime/build/index.js:1299:24)
at Runtime._loadModule (/home/vsts/work/1/s/node_modules/jest-runtime/build/index.js:898:12)
at Runtime.requireModule (/home/vsts/work/1/s/node_modules/jest-runtime/build/index.js:746:10)
```

</details>

<details>
<summary>Click to show screenshots</summary>

![image](https://user-images.githubusercontent.com/1622400/118036372-58339400-b321-11eb-9f55-f6302f057426.png)

![image](https://user-images.githubusercontent.com/1622400/118036407-5f5aa200-b321-11eb-9c3e-c4b1c1111d58.png)

</details>

## Archived tests

<details>
<summary>Click to expand</summary>

### `__tests__/html/transcript.navigation.upArrowOnTerminator.js › transcript navigation should focus the last activity when press up arrow key on the terminator`

https://fuselabs.visualstudio.com/BotFramework-WebChat/_build/results?buildId=230398&view=ms.vss-test-web.build-test-results-tab&runId=4384744&resultId=100849&paneView=asg-cloudtest.asg-cloudtest-attachments.asg-cloudtest.asg-cloudtest-attachments&path=transcript-navigation-up-arrow-on-terminator-js-transcript-navigation-should-focus-the-last-activity-when-press-up-arrow-key-on-the-terminator-1-diff.png

![image](https://user-images.githubusercontent.com/1622400/113382297-05d08200-9336-11eb-916c-b39e701e3038.png)

### `__tests__/html/hooks.useTextBox.js`

> https://fuselabs.visualstudio.com/BotFramework-WebChat/_build/results?buildId=216358&view=ms.vss-test-web.build-test-results-tab&runId=4130302&resultId=100853&paneView=asg-cloudtest.asg-cloudtest-attachments.asg-cloudtest.asg-cloudtest-attachments&path=hooks-use-text-box-js-use-text-box-should-work-properly-1-diff.png

[`__tests__/html/hooks.useTextBox.js`](../blob/master/__tests__/html/hooks.useTextBox.js) › useTextBox should work properly

![image](https://user-images.githubusercontent.com/1622400/108888954-a2c62f80-75c0-11eb-94fe-cb16b06c90b9.png)

<details>
<summary>Stack trace</summary>
<pre>
Error: Expected image to match or be a close match to snapshot but was 5.489583333333333% different from snapshot (12648 differing pixels).
See diff for details: /home/vsts/work/1/s/tests/image_snapshots/html/diff_output/hooks-use-text-box-js-use-text-box-should-work-properly-1-diff.png
at _callee3$ (/home/vsts/work/1/s/tests/html/jest/runPageProcessor.js:92:49)
at tryCatch (/home/vsts/work/1/s/node_modules/regenerator-runtime/runtime.js:63:40)
at Generator.invoke [as _invoke] (/home/vsts/work/1/s/node_modules/regenerator-runtime/runtime.js:293:22)
at Generator.next (/home/vsts/work/1/s/node_modules/regenerator-runtime/runtime.js:118:21)
at asyncGeneratorStep (/home/vsts/work/1/s/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
at _next (/home/vsts/work/1/s/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
</pre>
</details>

### `__tests__/focus.js`

> https://fuselabs.visualstudio.com/BotFramework-WebChat/_build/results?buildId=216123&view=ms.vss-test-web.build-test-results-tab&runId=4126816&resultId=100226&paneView=debug

[`__tests__/focus.js`](../blob/master/__tests__/focus.js) › type focus sink should not paste in the send box when focus is on a text box of an Adaptive Card

![image](https://user-images.githubusercontent.com/1622400/108757643-f4a68100-74fe-11eb-8449-b853e3741edc.png)

<details>
<summary>Stack trace</summary>
<pre>
Error: Expected image to match or be a close match to snapshot but was 8.089409722222223% different from snapshot (18638 differing pixels).
See diff for details: /home/vsts/work/1/s/tests/image_snapshots/chrome-docker/diff_output/focus-js-type-focus-sink-should-not-paste-in-the-send-box-when-focus-is-on-a-text-box-of-an-adaptive-card-1-diff.png
at _callee7$ (/home/vsts/work/1/s/tests/focus.js:162:23)
at tryCatch (/home/vsts/work/1/s/node_modules/regenerator-runtime/runtime.js:63:40)
at Generator.invoke [as _invoke] (/home/vsts/work/1/s/node_modules/regenerator-runtime/runtime.js:293:22)
at Generator.next (/home/vsts/work/1/s/node_modules/regenerator-runtime/runtime.js:118:21)
at asyncGeneratorStep (/home/vsts/work/1/s/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
at _next (/home/vsts/work/1/s/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
</pre>
</details>

### `__tests__/rtl.js`

[`__tests__/rtl.js`](https://github.com/microsoft/BotFramework-WebChat/blob/master/__tests__/rtl.js) › rtl UI carousel should scroll to the left instead of right

https://fuselabs.visualstudio.com/BotFramework-WebChat/_build/results?buildId=214610&view=ms.vss-test-web.build-test-results-tab&runId=4095202&resultId=100388&paneView=attachments

<details>
<summary>Stack trace</summary>
<pre>
Error: Expected image to match or be a close match to snapshot but was 1.9049479166666667% different from snapshot (4389 differing pixels).
See diff for details: /home/vsts/work/1/s/tests/image_snapshots/chrome-docker/diff_output/rtl-js-rtl-ui-carousel-should-scroll-to-the-left-instead-of-right-1-diff.png
</pre>
</details>

![image](https://user-images.githubusercontent.com/1622400/108246895-d4458380-7106-11eb-87b5-0c90b2477120.png)

### `__tests__/html/transcript.navigation.focusActivity.byClick.js`

[`__tests__/html/transcript.navigation.focusActivity.byClick.js`](https://github.com/microsoft/BotFramework-WebChat/blob/master/__tests__/html/transcript.navigation.focusActivity.byClick.js) › transcript navigation should focus activity by click

https://fuselabs.visualstudio.com/BotFramework-WebChat/_build/results?buildId=214897&view=ms.vss-test-web.build-test-results-tab&runId=4103986&resultId=100867&paneView=debug

<details>
<summary>Stack trace</summary>
<pre>
Error: Expected image to match or be a close match to snapshot but was 15.813802083333334% different from snapshot (36435 differing pixels).
See diff for details: /home/vsts/work/1/s/tests/image_snapshots/html/diff_output/transcript-navigation-focus-activity-by-click-js-transcript-navigation-should-focus-activity-by-click-1-diff.png
at _callee3$ (/home/vsts/work/1/s/tests/html/jest/runPageProcessor.js:92:49)
at tryCatch (/home/vsts/work/1/s/node_modules/regenerator-runtime/runtime.js:63:40)
</pre>
</details>

![image](https://user-images.githubusercontent.com/1622400/108342813-14047d80-7190-11eb-8bac-6253b80c1fb6.png)

### `__tests__/html/transcript.navigation.focusActivity.focusCard.js`

[`
__tests__/html/transcript.navigation.focusActivity.focusCard.js`](https://github.com/microsoft/BotFramework-WebChat/blob/master/__tests__/html/transcript.navigation.focusActivity.focusCard.js) › transcript navigation should focus activity and focus on card

https://fuselabs.visualstudio.com/BotFramework-WebChat/_build/results?buildId=214596&view=ms.vss-test-web.build-test-results-tab&runId=4094814&resultId=100837&paneView=attachments

<details>
<summary>Stack trace</summary>
<pre>
Error: Expected image to match or be a close match to snapshot but was 13.457031250000002% different from snapshot (31005 differing pixels).
See diff for details: /home/vsts/work/1/s/tests/image_snapshots/html/diff_output/transcript-navigation-focus-activity-focus-card-js-transcript-navigation-should-focus-activity-and-focus-on-card-3-diff.png
</pre>
</details>

![image](https://user-images.githubusercontent.com/1622400/108227361-ab1af800-70f2-11eb-9731-5ba566d45adb.png)

### `__tests__/html/hooks.useScrollToEnd.hideNewMessagesButton.js`

[`__tests__/html/hooks.useScrollToEnd.hideNewMessagesButton.js`](https://github.com/microsoft/BotFramework-WebChat/blob/master/__tests__/html/hooks.useScrollToEnd.hideNewMessagesButton.js) › useScrollToEnd.hideNewMessagesButton should scroll to end and hide "New Messages" button

<details>
<summary>Stack trace</summary>
<pre>
Error: Unhandled exception from the test code on the page.

Error: Test code timed out while waiting for "New message button is shown".
at http://webchat2/dist/testharness.js:1:171438
at _loop$ (/home/vsts/work/1/s/tests/html/jest/createJobObservable.js:47:13)
at tryCatch (/home/vsts/work/1/s/node_modules/regenerator-runtime/runtime.js:63:40)
</pre>
</details>

### `__tests__/html/hooks.useObserveScrollPosition.js`

[`__tests__/html/hooks.useObserveScrollPosition.js`](https://github.com/microsoft/BotFramework-WebChat/blob/master/__tests__/html/hooks.useObserveScrollPosition.js) › useObserveScrollPosition should observe scroll position changes

https://fuselabs.visualstudio.com/BotFramework-WebChat/_build/results?buildId=214476&view=ms.vss-test-web.build-test-results-tab&runId=4094252&resultId=100796&paneView=debug

<details>
<summary>Stack trace</summary>
<pre>
Error: Unhandled exception from the test code on the page.

Error: Test code timed out while waiting for "scroll stabilized after 5 counts".
at http://webchat2/dist/testharness.js:1:171438
at _loop$ (/home/vsts/work/1/s/tests/html/jest/createJobObservable.js:47:13)
at tryCatch (/home/vsts/work/1/s/node_modules/regenerator-runtime/runtime.js:63:40)
at Generator.invoke [as _invoke] (/home/vsts/work/1/s/node_modules/regenerator-runtime/runtime.js:293:22)
at Generator.next (/home/vsts/work/1/s/node_modules/regenerator-runtime/runtime.js:118:21)
</pre>
</details>

### Tests for audio attachment

Add test for `<AudioAttachment>` and `<AudioContent>`.

### Tests for send box

- Hover/focus state styles

### Take a screenshot when wait condition failed

Take a screenshot when wait condition failed to better understand where it failed.

### `hero card actions / messageBack (value)`

<details>
<summary>Stack trace</summary>
<pre>
Error: Unhandled exception from the test code on the page.

TypeError: Failed to fetch
at _loop$ (/home/vsts/work/1/s/tests/html/jest/createJobObservable.js:47:13)
at tryCatch (/home/vsts/work/1/s/node_modules/regenerator-runtime/runtime.js:63:40)
at Generator.invoke [as _invoke] (/home/vsts/work/1/s/node_modules/regenerator-runtime/runtime.js:293:22)
at Generator.next (/home/vsts/work/1/s/node_modules/regenerator-runtime/runtime.js:118:21)
at tryCatch (/home/vsts/work/1/s/node_modules/regenerator-runtime/runtime.js:63:40)
at maybeInvokeDelegate (/home/vsts/work/1/s/node_modules/regenerator-runtime/runtime.js:356:18)
at Generator.invoke [as _invoke] (/home/vsts/work/1/s/node_modules/regenerator-runtime/runtime.js:267:32)
at Generator.next (/home/vsts/work/1/s/node_modules/regenerator-runtime/runtime.js:118:21)
at asyncGeneratorStep (/home/vsts/work/1/s/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
at _next (/home/vsts/work/1/s/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
</pre>
</details>

</details>

## Resolved

<details>
<summary>Click to expand</summary>

The following lists are tests that were improved.

### `toaster-js-move-recently-updated-toast-to-the-top-1-diff.png`

> Fixed in https://github.com/microsoft/BotFramework-WebChat/commit/a496e580e7b215c560f1acfbd26619c0fb7eaf4e#diff-e7d82c12061dc9bc05ad1e6fb02fe1f541f52258976cb93720e9ef7278e03258.

![image](https://user-images.githubusercontent.com/1622400/75090885-54e59a00-551c-11ea-9ec7-ed9d34e449e2.png)

### `__tests__/html/offlineUI.firstConnect.js`

> Fixed in #3723.

Image is too slow to show up.

![image](https://user-images.githubusercontent.com/1622400/84325761-591bde80-ab30-11ea-8206-08052639ca7c.png)

### `html/cardAction.adaptiveCard.disallowedScheme.js`

"openUrl" action on Adaptive Card with a disallowed scheme

```js
Error: Unhandled exception from the test code on the page.

Error: Test code timed out while waiting for "at least 2 activities is shown".
at http://webchat2/dist/testharness.js:1:4911
at _loop$ (/home/vsts/work/1/s/tests/html/jest/createJobObservable.js:47:13)
at tryCatch (/home/vsts/work/1/s/node_modules/regenerator-runtime/runtime.js:63:40)
at Generator.invoke [as _invoke] (/home/vsts/work/1/s/node_modules/regenerator-runtime/runtime.js:293:22)
at Generator.next (/home/vsts/work/1/s/node_modules/regenerator-runtime/runtime.js:118:21)
at tryCatch (/home/vsts/work/1/s/node_modules/regenerator-runtime/runtime.js:63:40)
at maybeInvokeDelegate (/home/vsts/work/1/s/node_modules/regenerator-runtime/runtime.js:356:18)
at Generator.invoke [as _invoke] (/home/vsts/work/1/s/node_modules/regenerator-runtime/runtime.js:267:32)
at Generator.next (/home/vsts/work/1/s/node_modules/regenerator-runtime/runtime.js:118:21)
at asyncGeneratorStep (/home/vsts/work/1/s/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
at _next (/home/vsts/work/1/s/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
```

### `__tests__/html/focusManagement.newMessageButton.receiveMessage.js`

> Fixed in #3723.

"focus management after receive text message"

```
Error: Expected image to match or be a close match to snapshot but was 20.97048611111111% different from snapshot (48316 differing pixels).
See diff for details: /home/vsts/work/1/s/tests/image_snapshots/html/diff_output/focus-management-new-message-button-receive-message-js-focus-management-after-receive-text-message-click-on-new-message-button-should-focus-on-send-box-1-diff.png
at _callee2$ (/home/vsts/work/1/s/tests/html/jest/runPageProcessor.js:79:49)
at tryCatch (/home/vsts/work/1/s/node_modules/regenerator-runtime/runtime.js:45:40)
at Generator.invoke [as _invoke] (/home/vsts/work/1/s/node_modules/regenerator-runtime/runtime.js:274:22)
at Generator.prototype.<computed> [as next] (/home/vsts/work/1/s/node_modules/regenerator-runtime/runtime.js:97:21)
at asyncGeneratorStep (/home/vsts/work/1/s/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
at _next (/home/vsts/work/1/s/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

![image](https://user-images.githubusercontent.com/1622400/87301172-f073a900-c4c3-11ea-935c-8ee4e3b167c0.png)

![image](https://user-images.githubusercontent.com/1622400/94190032-64d1ad80-fe60-11ea-9abf-1b1709b06f0b.png)

### `__tests__/html/accessibility.adaptiveCard.interactive.js › accessibility requirement interactive Adaptive Card should be focusable`

> Fixed in #3723.

![image](https://user-images.githubusercontent.com/1622400/106878339-b13ebc80-668e-11eb-8ef1-70d28e58772b.png)
[Enhancement]

### `scroll-to-bottom-js-show-new-messages-button-only-when-new-message-come-3-diff.png`

> Obsoleted.

![image](https://user-images.githubusercontent.com/1622400/76142864-98fd9200-6026-11ea-95a5-ad5131938663.png)

### `speech recognition using authorization token with Direct Line protocol / should recognize "Hello, World!".`

> External issue.

```js
: Timeout - Async callback was not invoked within the 30000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 30000 ms timeout specified by jest.setTimeout.Error:
at new Spec (/home/vsts/work/1/s/node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
at new Spec (/home/vsts/work/1/s/node_modules/jest-jasmine2/build/setup_jest_globals.js:78:9)
at specFactory (/home/vsts/work/1/s/node_modules/jest-jasmine2/build/jasmine/Env.js:523:24)
at Env.it (/home/vsts/work/1/s/node_modules/jest-jasmine2/build/jasmine/Env.js:592:24)
at Env.it (/home/vsts/work/1/s/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:134:23)
at test (/home/vsts/work/1/s/node_modules/jest-jasmine2/build/jasmine/jasmineLight.js:100:21)
at /home/vsts/work/1/s/tests/html/speechRecognition.simple.js:22:3
at Suite.<anonymous> (/home/vsts/work/1/s/node_modules/jest-each/build/bind.js:76:13)
at addSpecsToSuite (/home/vsts/work/1/s/node_modules/jest-jasmine2/build/jasmine/Env.js:444:51)
at Env.describe (/home/vsts/work/1/s/node_modules/jest-jasmine2/build/jasmine/Env.js:414:11)
```
</details>

**Comment by compulim** [comment]
All test reliability issues seems resolved. Closing this issue.
