### ISSUE TITLE
Unable to launch BotFramework-WebChat "playground" / npm-link into my project

### ISSUE THREAD

**Issue by cimbis** [microsoft/BotFramework-WebChat#3389]
I'd like to do some tinkering with some of WebChat components before I'm raising any other issues (or possibly a PR), however, I'm unable to launch the project - it results in errors. I have cloned master branch of repo, apparently it's the 4.9.3-0 version.

As per following suggestion in one of the previous issues:

> [..] I just cloned and built the repo with no issues. Are you following the steps listed in the build [docs](https://github.com/microsoft/BotFramework-WebChat/blob/master/docs/BUILD_SCRIPTS.md#build-scripts)? As they indicate, from the root directory you'll want to:
> 
> - Prep the repo by running
>     - `npm ci`
>     - `npm install`
> - Run `npm run bootstrap`
> - Run `npm run build`
> 
> _Originally posted by @stevkan in https://github.com/microsoft/BotFramework-WebChat/issues/3379#issuecomment-668735229_

Everything seems to be fine up until I run `npm start` (I've changed port on which the app should start to avoid conflict with other service that runs on my computer - I don't think it should cause any issues), which produces the following output:

```
1 verbose cli [
1 verbose cli   '/Users/jc/.nvm/versions/node/v12.14.1/bin/node',
1 verbose cli   '/Users/jc/.nvm/versions/node/v12.14.1/bin/npm',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.14.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle botframework-webchat-root@4.9.3-0~prestart: botframework-webchat-root@4.9.3-0
6 info lifecycle botframework-webchat-root@4.9.3-0~start: botframework-webchat-root@4.9.3-0
7 verbose lifecycle botframework-webchat-root@4.9.3-0~start: unsafe-perm in lifecycle true
8 verbose lifecycle botframework-webchat-root@4.9.3-0~start: PATH: /Users/jc/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/jc/DEV/BotFramework-WebChat/node_modules/.bin:/Users/jc/.nvm/versions/node/v12.14.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/jc/DEV/BotFramework-WebChat/node_modules/.bin
9 verbose lifecycle botframework-webchat-root@4.9.3-0~start: CWD: /Users/jc/DEV/BotFramework-WebChat
10 silly lifecycle botframework-webchat-root@4.9.3-0~start: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'concurrently --kill-others --raw "serve" "serve -p 9009 -c serve-test.json" "lerna run --ignore playground --parallel --stream start"'
10 silly lifecycle ]
11 silly lifecycle botframework-webchat-root@4.9.3-0~start: Returned: code: 1  signal: null
12 info lifecycle botframework-webchat-root@4.9.3-0~start: Failed to exec start script
13 verbose stack Error: botframework-webchat-root@4.9.3-0 start: `concurrently --kill-others --raw "serve" "serve -p 9009 -c serve-test.json" "lerna run --ignore playground --parallel --stream start"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/jc/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:223:5)
13 verbose stack     at ChildProcess.<anonymous> (/Users/jc/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:223:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid botframework-webchat-root@4.9.3-0
15 verbose cwd /Users/jc/DEV/BotFramework-WebChat
16 verbose Darwin 19.6.0
17 verbose argv "/Users/jc/.nvm/versions/node/v12.14.1/bin/node" "/Users/jc/.nvm/versions/node/v12.14.1/bin/npm" "start"
18 verbose node v12.14.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error botframework-webchat-root@4.9.3-0 start: `concurrently --kill-others --raw "serve" "serve -p 9009 -c serve-test.json" "lerna run --ignore playground --parallel --stream start"`
22 error Exit status 1
23 error Failed at the botframework-webchat-root@4.9.3-0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Hmm, okay, well, I tried killing the the service running on 5001, so that I can use that port for starting WebChat instance... _Same error.._ 
Then I thought maybe it has something to do with v4.9.3-0, so I `git fetch && git fetch --tags` and `git checkout v4.9.2`, set the solution with `npm ci` -> `npm i` -> `npm run bootstrap` -> `npm run build` -> `npm start`.. jeez..
Again, _same error_, diffrent version numbers.

Alright, if I'm unable to start the project (I'm assuming it runs the playground package, if my `package.json` "scripts" skills are correct), I've heard that I can link packages into my solution.

So, what I want to achieve - is to try out variations of components used to render the chat, specifically one of the issues I'm having in my project is that I don't want the screen reader to read out timestamps. It feels that developers of this repo can't really decide themselves whether or not it should be read out [#2226](https://github.com/microsoft/BotFramework-WebChat/pull/2226) and [#2018](https://github.com/microsoft/BotFramework-WebChat/pull/2018) . I don't really care about the reasoning why it's like that. I want to be able to customise such behaviour and therefore I would love to access the source of components so that I can modify their behaviour to my liking, make it configurable and create a PR for that (if it doesn't match the vision of library's developers I'd be glad to keep it in my personal fork).

Okay, now with my reasoning out the way, as I mentioned before, I'm unable to run the project, therefore I wanted to try out the package linking (never done it before - what could go wrong?) - after `ci | install | bootstrap | build` I'd `cd` into `packages/bundle` directory - seems to be the main "botframework-webchat" as per `package.json` "name" key.

So, as per [npm-link docs](https://docs.npmjs.com/cli/link):
➜  bundle git:(master) ✗ `npm link`
which spits out:
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for botframework-webchat-core@0.0.0-0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'bundle'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jc/.npm/_logs/2020-08-07T09_51_23_454Z-debug.log
```

No matching version ... @0.0.0-0 ... eh?
Oh really, the dependencies list `""botframework-*": "0.0.0-0"` 😳
But wait - the "version" listed in `packages/bundle/package.json` is also 0.0.0-0 - now I'm lost.

Okay, okay, I don't really need the bundle, I need the `botframework-webchat-component` to adjust the TimeStamp.js and check whether the screen reader behaves the way I want to:

➜  bundle git:(master) ✗ `cd ../component && npm link`
followed by
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for botframework-webchat-core@0.0.0-0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'component'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jc/.npm/_logs/2020-08-07T10_04_23_928Z-debug.log
```

not impressed 🙄

What if I just `npm install`?

`cd ~/DEV/my-custom-chat` -> `npm i ../BotFramework-WebChat/packages/component`

```
[..]
4244 warn botframework-webchat@0.0.0-0 had bundled packages that do not match the required version(s). They have been replaced with non-bundled versions.
4245 warn ajv-keywords@3.4.1 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
4246 warn botframework-webchat-component@0.0.0-0 requires a peer of react@^16.8.6 but none is installed. You must install peer dependencies yourself.
4247 warn botframework-webchat-component@0.0.0-0 requires a peer of react-dom@^16.8.6 but none is installed. You must install peer dependencies yourself.
4248 warn babel-loader@8.1.0 requires a peer of webpack@>=2 but none is installed. You must install peer dependencies yourself.
4249 warn babel-loader@8.1.0 requires a peer of webpack@>=2 but none is installed. You must install peer dependencies yourself.
4250 warn react-dictate-button@1.2.2 requires a peer of react@^16.4.1 but none is installed. You must install peer dependencies yourself.
4251 warn react-film@2.1.0 requires a peer of react@^16.8.6 but none is installed. You must install peer dependencies yourself.
4252 warn react-film@2.1.0 requires a peer of react-dom@^16.8.6 but none is installed. You must install peer dependencies yourself.
4253 warn react-redux@7.2.0 requires a peer of react@^16.8.3 but none is installed. You must install peer dependencies yourself.
4254 warn react-say@2.0.1-master.c5d6304 requires a peer of react@^16.8.6 but none is installed. You must install peer dependencies yourself.
4255 warn react-scroll-to-bottom@3.0.0 requires a peer of react@^16.8.6 but none is installed. You must install peer dependencies yourself.
4256 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
4257 warn enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/Users/jc/DEV/my-custom-chat/node_modules/.staging/fsevents-bf7840b8/node_modules/aproba' -> '/Users/jc/DEV/my-custom-chat/node_modules/.staging/aproba-3e68b35b'
4258 verbose enoent SKIPPING OPTIONAL DEPENDENCY: This is related to npm not being able to find a file.
4258 verbose enoent SKIPPING OPTIONAL DEPENDENCY:
4259 verbose stack Error: ENOENT: no such file or directory, rename '/Users/jc/DEV/my-custom-chat/node_modules/.staging/botframework-webchat-5628f055/node_modules/@babel/code-frame' -> '/Users/jc/DEV/my-custom-chat/node_modules/.staging/@babel/code-frame-8abfb7a6'
4260 verbose cwd /Users/jc/DEV/my-custom-chat
4261 verbose Darwin 19.6.0
4262 verbose argv "/Users/jc/.nvm/versions/node/v12.14.1/bin/node" "/Users/jc/.nvm/versions/node/v12.14.1/bin/npm" "i" "../../../BotFramework-WebChat/packages/bundle"
4263 verbose node v12.14.1
4264 verbose npm  v6.13.4
4265 error code ENOENT
4266 error syscall rename
4267 error path /Users/jc/DEV/my-custom-chat/node_modules/.staging/botframework-webchat-5628f055/node_modules/@babel/code-frame
4268 error dest /Users/jc/DEV/my-custom-chat/node_modules/.staging/@babel/code-frame-8abfb7a6
4269 error errno -2
4270 error enoent ENOENT: no such file or directory, rename '/Users/jc/DEV/my-custom-chat/node_modules/.staging/botframework-webchat-5628f055/node_modules/@babel/code-frame' -> '/Users/jc/DEV/my-custom-chat/node_modules/.staging/@babel/code-frame-8abfb7a6'
4271 error enoent This is related to npm not being able to find a file.
4272 verbose exit [ -2, true ]
```

Something about wrong versions of dependencies?
`my-custom-chat/package.json`:

```
{
  "name": "my-custom-chat",
  "description": "",
  "private": true,
  "dependencies": {
    "@mdi/js": "^4.7.95",
    "@mdi/react": "^1.2.1",
    "@microsoft/applicationinsights-react-js": "^2.5.4",
    "@microsoft/applicationinsights-web": "^2.5.4",
    "abort-controller": "^3.0.0",
    "botframework-webchat": "^4.9.2",
    "classnames": "^2.2.6",
    "core-js": "^2.6.9",
    "css-vars-ponyfill": "^2.1.1",
    "file-saver": "^2.0.2",
    "focus-trap-react": "^6.0.0",
    "http-proxy": "^1.18.0",
    "moment": "^2.27.0",
    "query-string": "^6.7.0",
    "react": "^16.13.1",
    "react-app-polyfill": "^1.0.6",
    "react-day-picker": "^7.4.5",
    "react-dom": "^16.13.1",
    "react-dropzone": "^10.2.1",
    "react-ga": "^3.1.2",
    "react-gtm-module": "^2.0.10",
    "react-markdown": "^4.3.1",
    "react-redux": "^7.2.1",
    "react-remove-scroll": "^2.3.0",
    "react-router-dom": "^5.2.0",
    "react-scripts": "^3.4.1",
    "react-transition-group": "^4.3.0",
    "redux": "^4.0.5",
    "redux-persist": "^5.10.0",
    "redux-persist-transform-filter": "0.0.18",
    "redux-saga": "^1.0.3",
    "scroll-into-view-if-needed": "^2.2.24"
  },
  "devDependencies": {
    "@testing-library/jest-dom": "^5.11.2",
    "@testing-library/react": "^10.4.7",
    "@testing-library/react-hooks": "^3.4.1",
    "@types/classnames": "^2.2.8",
    "@types/core-js": "^2.5.1",
    "@types/enzyme": "^3.10.5",
    "@types/enzyme-adapter-react-16": "^1.0.6",
    "@types/file-saver": "^2.0.1",
    "@types/jest": "^25.2.3",
    "@types/markdown-it": "0.0.7",
    "@types/node": "^10.14.8",
    "@types/query-string": "^6.3.0",
    "@types/react": "^16.9.34",
    "@types/react-dom": "^16.9.6",
    "@types/react-gtm-module": "^2.0.0",
    "@types/react-redux": "^7.1.7",
    "@types/react-router-dom": "^4.3.3",
    "@types/react-transition-group": "^2.9.2",
    "@types/redux-mock-store": "^1.0.2",
    "@types/redux-persist": "^4.3.1",
    "@types/redux-persist-transform-filter": "0.0.4",
    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16": "^1.15.2",
    "enzyme-to-json": "^3.5.0",
    "eslint": "^6.8.0",
    "express": "^4.17.1",
    "husky": "^1.3.1",
    "jest-mock-console": "^1.0.1",
    "lint-staged": "^8.2.0",
    "node-sass": "^4.12.0",
    "prettier": "^2.0.5",
    "redux-devtools-extension": "^2.13.8",
    "redux-mock-store": "^1.5.4",
    "redux-saga-test-plan": "^4.0.0-beta.3",
    "tslib": "^1.11.1",
    "tslint": "^5.18.0",
    "tslint-config-prettier": "^1.18.0",
    "tslint-react": "^4.2.0",
    "typesafe-actions": "^3.4.0",
    "typescript": "^3.8.3"
  },
  "optionalDependencies": {
    "fsevents": "1.2.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "format": "prettier --write \"src/**/*.{js,jsx,ts,tsx,json}\"",
    "serve": "node serve.ts"
  }
}
```

So, two questions:
1. how do I `npm start` "BotFramework-WebChat" project?
2. how do I correctly link individual packages into my own project?

**Comment by stevkan** [comment]
@cimbis, unfortunately, I am unable to repro the issue you are facing. Can you tell me which version of Node and npm you have installed? I'm using v14.6.0 and v6.14.5, respectively. Also, if you haven't already, can you try cloning the repo in your system's root directory in case long directory paths/filenames are part of the issue?

**Comment by stevkan** [comment]
With regards to `npm link`, that command is run in the repo's root directory: `...\BotFramework-WebChat\`. However, if you encounter errors trying to build, likely running 'npm link' and/or 'npm link botframework-webchat' (in your projects root directory) will also fail.

**Comment by cimbis** [comment]
Hmm.. I'm on node v12.something.something - I'm unable to tell as I don't have my work laptop on me right now and won't have access to it during weekend as well (excuse me for not including that in my initial post). I'll also try to build it with the version you're using - v14.6.0.

As for `npm link` - thanks for pointing out that it should be run from `BotFramework-WebChat` root.

I'll try out your suggestions once I get back to my battle station and will get back to you with results, thank you!

**Comment by cimbis** [comment]
Heh, realised that the very first lines of the log I posted mention node/npm versions I'm running:


```
2 info using npm@6.13.4
3 info using node@v12.14.1
```

FYI, @stevkan

**Comment by cimbis** [comment]
Alright, my findings:

**node 14.6.0**
```
➜  BotFramework-WebChat git:(master) ✗ nvm use 14
Now using node v14.6.0 (npm v6.14.6)
```

from BotFramework-WebChat root:
```
➜  BotFramework-WebChat git:(master) ✗ npm ci && npm i && npm run bootstrap && npm run build
```

```
➜  BotFramework-WebChat git:(master) ✗ npm link
audited 1543 packages in 6.699s

54 packages are looking for funding
  run `npm fund` for details

found 17 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
/Users/jc/.nvm/versions/node/v14.6.0/lib/node_modules/botframework-webchat-root -> /Users/jc/DEV/BotFramework-WebChat
```

then in my solution:
```
➜  the-chat git:(feature/custom-chat) ✗ npm link botframework-webchat
/Users/jc/DEV/secret-path-to-my-solution/node_modules/botframework-webchat -> /Users/jc/.nvm/versions/node/v14.6.0/lib/node_modules/botframework-webchat
```

Which yields nothing, `node_modules` are not updated. It seems to me that the issue might be in the fact that `npm link` sees *botframework-webchat-root* as a package name in `BotFrameWork-WebChat/package.json`...?

---

Result from **node 12.14.1**:

```
➜  BotFramework-WebChat git:(master) ✗ nvm use 12
Now using node v12.14.1 (npm v6.13.4)
```

```
➜  BotFramework-WebChat git:(master) ✗ npm ci && npm i && npm run bootstrap && npm run build
```

```
➜  BotFramework-WebChat git:(master) ✗ npm link
audited 1543 packages in 6.145s

52 packages are looking for funding
  run `npm fund` for details

found 17 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
/Users/jc/.nvm/versions/node/v12.14.1/lib/node_modules/botframework-webchat-root -> /Users/jc/DEV/BotFramework-WebChat
```

and in my soluition:
```
➜  the-chat git:(feature/custom-chat) ✗ npm link botframework-webchat
npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated @types/vfile-message@2.0.0: This is a stub types definition. vfile-message provides its own type definitions, so you do not need this installed.

> core-js@3.6.4 postinstall /Users/jc/.nvm/versions/node/v12.14.1/lib/node_modules/botframework-webchat/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
  > https://opencollective.com/core-js
  > https://www.patreon.com/zloirock

  Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> abort-controller-es5@1.1.0 postinstall /Users/jc/.nvm/versions/node/v12.14.1/lib/node_modules/botframework-webchat/node_modules/abort-controller-es5
> npx -p webpack-cli@3.3.11 -p webpack@4.43.0 webpack-cli --config webpack-lib.config.js

Hash: 09466cb1a612f219d046
Version: webpack 4.43.0
Time: 1105ms
Built at: 08/10/2020 3:58:03 PM
Asset      Size  Chunks             Chunk Names
index.js  32.1 KiB       0  [emitted]  index
Entrypoint index = index.js
  [0] ./src/index.js + 2 modules 28 KiB {0} [built]
| ./src/index.js 480 bytes [built]
| ../abort-controller/dist/abort-controller.mjs 6.5 KiB [built]
| ../event-target-shim/dist/event-target-shim.mjs 21 KiB [built]

> event-target-shim-es5@1.1.0 postinstall /Users/jc/.nvm/versions/node/v12.14.1/lib/node_modules/botframework-webchat/node_modules/event-target-shim-es5
> npx -p webpack-cli@3.3.11 -p webpack@4.43.0 webpack-cli --config webpack-lib.config.js

Hash: ec965ee7da31f66c8c86
Version: webpack 4.43.0
Time: 1082ms
Built at: 08/10/2020 3:58:18 PM
Asset      Size  Chunks                   Chunk Names
index.js  25.2 KiB       0  [emitted]        index
index.js.map  40.3 KiB       0  [emitted] [dev]  index
Entrypoint index = index.js index.js.map
  [0] ./src/index.js + 1 modules 21.2 KiB {0} [built]
| ./src/index.js 144 bytes [built]
| ../event-target-shim/dist/event-target-shim.mjs 21 KiB [built]

> p-defer-es5@1.1.0 postinstall /Users/jc/.nvm/versions/node/v12.14.1/lib/node_modules/botframework-webchat/node_modules/p-defer-es5
> npx -p webpack-cli@3.3.11 -p webpack@4.43.0 webpack-cli --config webpack-lib.config.js

Hash: 5b9e700fb781643b3a30
Version: webpack 4.43.0
Time: 447ms
Built at: 08/10/2020 3:58:31 PM
Asset      Size  Chunks             Chunk Names
index.js  4.33 KiB       0  [emitted]  index
Entrypoint index = index.js
  [0] ../p-defer/index.js 246 bytes {0} [built]
  [1] ./src/index.js 68 bytes {0} [built]

> markdown-it-attrs-es5@1.1.0 postinstall /Users/jc/.nvm/versions/node/v12.14.1/lib/node_modules/botframework-webchat/node_modules/markdown-it-attrs-es5
> npx -p webpack-cli@3.3.11 -p webpack@4.43.0 webpack-cli --config webpack-lib.config.js

Hash: d0cd665930885f4636e3
Version: webpack 4.43.0
Time: 903ms
Built at: 08/10/2020 3:58:47 PM
Asset      Size  Chunks             Chunk Names
index.js  9.56 KiB       0  [emitted]  index
Entrypoint index = index.js
  [0] ../markdown-it-attrs/index.js 5.43 KiB {0} [built]
  [1] ./src/index.js 80 bytes {0} [built]
  [2] ../markdown-it-attrs/patterns.js 8.53 KiB {0} [built]
  [3] ../markdown-it-attrs/utils.js 7.38 KiB {0} [built]
npm WARN botframework-webchat@4.9.2 requires a peer of react@^16.8.6 but none is installed. You must install peer dependencies yourself.
  npm WARN botframework-webchat@4.9.2 requires a peer of react-dom@^16.8.6 but none is installed. You must install peer dependencies yourself.
  npm WARN botframework-webchat-component@4.9.2 requires a peer of react@^16.8.6 but none is installed. You must install peer dependencies yourself.
  npm WARN botframework-webchat-component@4.9.2 requires a peer of react-dom@^16.8.6 but none is installed. You must install peer dependencies yourself.
  npm WARN babel-loader@8.1.0 requires a peer of webpack@>=2 but none is installed. You must install peer dependencies yourself.
  npm WARN react-film@2.1.0 requires a peer of react@^16.8.6 but none is installed. You must install peer dependencies yourself.
  npm WARN react-film@2.1.0 requires a peer of react-dom@^16.8.6 but none is installed. You must install peer dependencies yourself.
  npm WARN react-dictate-button@1.2.2 requires a peer of react@^16.4.1 but none is installed. You must install peer dependencies yourself.
  npm WARN react-redux@7.2.0 requires a peer of react@^16.8.3 but none is installed. You must install peer dependencies yourself.
  npm WARN react-say@2.0.1-master.c5d6304 requires a peer of react@^16.8.6 but none is installed. You must install peer dependencies yourself.
  npm WARN react-scroll-to-bottom@3.0.0 requires a peer of react@^16.8.6 but none is installed. You must install peer dependencies yourself.

+ botframework-webchat@4.9.2
added 354 packages from 326 contributors in 92.421s
/Users/jc/DEV/secret-path-to-my-solution/node_modules/botframework-webchat -> /Users/jc/.nvm/versions/node/v12.14.1/lib/node_modules/botframework-webchat
```

Alright, now judging by the output it does look like something that could work. I see that `node_modules` are updated with `botframework-webchat`. Interestingly enough that this time `npm-link` named the reference `botframework-webchat` unlike previously `botframework-webchat-root` on node 14.6.0.

Okay, seems that it's time for `npm start`:
```
Failed to compile.

/Users/jc/DEV/secret-path-to-my-solution/src/components/SomeComp.tsx
TypeScript error in /Users/jc/DEV/secret-path-to-my-solution/src/components/SomeComp.tsx(25,25):
Cannot find module 'botframework-directlinejs'.  TS2307

    23 | import { KeyCodes } from '../../../constants';
    24 | import { translate, Translations } from '../../../locale';
  > 25 | import { Message } from 'botframework-directlinejs';
       |                         ^
    26 | import { Dispatch } from 'redux';
    27 | import { sortActivitiesByTimeStamp } from './editHelper';
    28 |
```

Which tells me that something is still wrong, as node is unable to find `botframework-directlinejs` 🙄

Any thoughts on the above @stevkan?

**Comment by stevkan** [comment]
@cimbis, Can you link me to the node version manager you are using. I can't imagine that is the source of the problem, but I want to rule that out. Also, have you tried a fresh clone of the repo, in case something got muddled while cloning the first time?

**Comment by cimbis** [comment]
I'm currently running:
```
➜  ~ nvm --version
0.35.3
```

And yes, I've fruitlesslys tried re-cloning the repo before setting up the WebChat project with other node versions.

**Comment by stevkan** [comment]
@cimbis, I know you are using `nvm`, but have you made any changes to the .npmrc (or equivalent) file that is changing how Node is running on your machine?

As for building the repo, could you try the following to see if any make a difference:

- Building with elevated rights?
- Not using `nvm` and instead use a direct install of Node?
- Attempting on a different machine you have access to?

@compulim, do you have any thoughts that might assist the customer on this?

**Comment by compulim** [comment]
We are using [lerna](https://github.com/lerna/lerna#readme) for monorepo management. It handle `npm link` and other symlink/junction automatically. When you run `npm run bootstrap`, it run `lerna bootstrap`, which actually do the following:

- Go to every `packages/*` folder, then run the following
   - Backup `package.json`
   - Remove peer packages from `package.json`
      - For example, in `packages/component/`, it remove `botframework-webchat-core` under `dependencies`. This is because the package is a peer at `/packages/core/`
   - Run `npm install`
   - Restore the backup `package.json`
- Go to every `packages/*` folder again after all `npm install` are done
   - Build symlink for every peer packages
      - For example, as `package/component/` depends on `packages/core/`
      - `cd packages/component/node_modules`
      - `mklink /j botframework-webchat-core ../../core`

So, after your ran `npm run bootstrap`, you should see:

- `packages/component/node_modules` is populated with tons of packages
- `packages/component/node_modules/botframework-webchat-core` is a symlink/junction to `packages/core`

You should not need to handle `npm link` or symlink yourself.

If you don't see this, please check why `lerna bootstrap` failed to do so.

I am trying out on a "new machine" by using Docker on a Node.js 14.6.0 image on Linux. I start a new machine by running:

```sh
docker run --entrypoint bash -it --rm -p 3000:3000 node:14.6.0
```

> This means, run `node:14.6.0` image, using `bash` shell, interactive with terminal, remove/cleanup after exit, expose port 3000 as port 3000.

Then, after it started:

```sh
cd ~
git clone https://github.com/microsoft/BotFramework-WebChat.git
cd BotFramework-WebChat
npm install
npm run bootstrap
npm run build
cd packages/playground
npm start
```

Will report more here when it's done.

**Comment by compulim** [comment]
I tested the fresh clone and build inside a brand new Linux box and it works. @cimbis could you see if there are any variations from your building steps?

FYI, we have few active development environments: Windows 10, Linux via WSL2, and Linux via Docker (for CI only). And all looks good to us.

Do you think this issue is specific to macOS?

**Comment by stevkan** [comment]
Closing due to a lack of activity. If the problem persists, please feel free to reopen.
