### ISSUE TITLE
webchat is not Loading giving blank screen

### ISSUE THREAD

**Issue by sukeerthimulakala** [microsoft/BotFramework-WebChat#4486]
Hi Team,

I am using the microsoft BotFramwork-webchat and using https://cdn.botframework.com/botframework-webchat/latest/webchat.js
am getting blank screen on first load and if i refresh the page, webchat is loading fine.
This is the error when blank screen comes
Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node. in webchat
    at ua (https://cdn.botframework.com/botframework-webchat/4.14.1/webchat.js:2:3544863)
    at xa (https://cdn.botframework.com/botframework-webchat/4.14.1/webchat.js:2:3549532)
    at ja (https://cdn.botframework.com/botframework-webchat/4.14.1/webchat.js:2:3553219)
    at https://cdn.botframework.com/botframework-webchat/4.14.1/webchat.js:2:3571078
![image](https://user-images.githubusercontent.com/36460075/199622541-ef8daf82-e538-484a-a92e-99d06d7b1f63.png)

After checking the resolution from this ticket https://github.com/microsoft/BotFramework-WebChat/issues/4196, I have downloaded to 4.14.1 ,but still am getting same issue.

Could you please help me to resolve this issue as its very high priority for me to resolve this?

Thanks,
Sukeerthi

**Comment by sukeerthimulakala** [comment]
Hi Team, Kindly look into the issue?

**Comment by stevkan** [comment]
@sukeerthimulakala, I am unable to repro the issue. Are you able to provide a copy of the Web Chat code you are using? This will make it easier to diagnose what is happening.

**Comment by sukeerthimulakala** [comment]
Hi @stevkan ,

below is the render chatbot code

 window.WebChat.renderWebChat(
                {
                    directLine: window.WebChat.createDirectLine({
                        token: token,
                        webSockets: true,
                        watermark: 10
                    }),
                    styleOptions
                    
                },
                document.getElementById('iframeid')
            );
            document.querySelector('#iframeid > *').focus();

**Comment by stevkan** [comment]
@sukeerthimulakala,

Unfortunately, that isn't enough for me to determine what might be the cause as everything there looks seemingly alright.

Are you able to share more (or all) of your page's code as it pertains to Web Chat (styleOptions, how you create the token (minus any keys), etc.)?

Also, how is the Web Chat being used with respect to the `iframe` (this might be revealed in any additional code you send)?

**Comment by sukeerthimulakala** [comment]
Hi @stevkan 

please find the attached file.

[botcode.txt](https://github.com/microsoft/BotFramework-WebChat/files/9931901/botcode.txt)

Thanks

**Comment by stevkan** [comment]
@sukeerthimulakala,

I don't know if this is the exact cause of the issue as the code you sent isn't complete so I can't run it as-is. However, I was able to hack it a bit to work with my setup, as shown below. And it works without issue.

There are two primary differences between your code and mine.

First, I had to replace the internals of `getDirectLinetoken()` with my code (shown at bottom) that calls a token server I have running. Additionally, I had to adjust the `response` property names to be camel case in `onGetTokenDone()` so the associated `token` and `conversationId` properties could be read.

Not knowing how `getDirectLinetoken()` is called, I simply did the following:

`window.onload = getDirectLinetoken();`

Second, I async/awaited the `getDirectLinetoken()` function and the internal calls and I believe this is the actual issue in your case. I believe the page doesn't load initially because the API call to get the token and store it in sessionStorage is still resolving. When you refresh, the values have been retrieved and stored by then which allows Web Chat to load.

```js
window.onload =  getDirectLinetoken();

// async/awaited the function
async function getDirectLinetoken( callBackFunction ) {
  const res = await fetch( 'http://localhost:3500/directline/conversations', { method: 'POST' } );
  const response = await res.json();
  await onGetTokenDone(response);
}

// 'response' properties were changed to camel case to match my API response
function onGetTokenDone( response ) {
  sessionStorage[ 'token' ] = response.token;
  sessionStorage[ 'conversation_Id' ] = response.conversationId;
  token = response.token;
  conversation_Id = response.conversationId;

  [...other code]
}
```

Please try adjusting your code to do something similar to the above, whether that is using async/await, promises, or something else, and let me know. I suspect that this will solve your issue.

**Comment by sukeerthimulakala** [comment]
Hi @stevkan ,
Apologies for delay, I will try above solution and let you know as soon as possible.
Many Thanks

**Comment by sukeerthimulakala** [comment]
Hi @stevkan ,

Many thanks for your time and effort.
I have implemented and tested in my local so far working fine, but it was happening earlier also randomly and need to deploy in staging environments and test thoroughly (it would take time from my end). I will let you know once it's done testing. 

Thanks

**Comment by sukeerthimulakala** [comment]
Hi @stevkan 

Apologies for delay,I have deployed and still am getting same issue randomly. I have also modified code as attached and still facing same error.
Regarding responses we have created Model and converted to Token and ConversationId Model properties so this camel case does not an issue. I have added console logs for each call. Please find the logs as well.
This issue happens randomly not every time.
Kindly look into that attached file.
[botcode-updated.txt](https://github.com/microsoft/BotFramework-WebChat/files/9996246/botcode-updated.txt)

**Comment by stevkan** [comment]
@sukeerthimulakala - thank you for your patience!

I looked at your included code and I believe the issue is a bit of a race condition. Because you don't appear to be using promises or async/await, sometimes the page is able to get and store the `token` and `conversationId` before Web Chat needs it. Other times, Web Chat is loaded first before those values are stored and made available resulting in a blank screen.

If you look at the [01.getting-started/b.minimal-bundle](https://github.com/microsoft/BotFramework-WebChat/blob/main/samples/01.getting-started/b.minimal-bundle/index.html#L43) sample you can see that the Web Chat code is wrapped in an _`async`_ function. And within the script the calls on lines 49 and 50 are both _`await`_ ed.

As your code is a bit more complex, you may need to play with it some to get the calls just right mostly around the getting and setting of DirectLine credentials.

Please look over the provided [samples](https://github.com/microsoft/BotFramework-WebChat/tree/main/samples) for reference. They may provide insight on changes that could benefit you.

**Comment by stevkan** [comment]
Closing due to inactivity. Please feel free to reopen if the issue persists or you have new details to share.
