### ISSUE TITLE
Timestamp Not Appearing Intermittently on IC3

### ISSUE THREAD

**Issue by kevinlin98z** [microsoft/BotFramework-WebChat#4621]
### Is it an issue related to Adaptive Cards?

No

### Is this an accessibility issue?

No

### What version of Web Chat are you using?

I am not using latest

### Which distribution are you using Web Chat from?

Bundle (webchat.js)

### Which hosting environment does this issue primarily affect?

Dynamics 365 Omnichannel

### Which browsers and platforms do the issue happened?

Browser: Edge (latest), Browser: Chrome (latest)

### Which area does this issue affect?

Others or unrelated

### What is the public URL for the website?

https://kevinlinclientdev.blob.core.windows.net/htmls/lcw-gcc-no-chatadaptershim.html

### Please describe the bug

Occasionally when sending messages on IC3, there is no timestamp / delivery status below the message in the UI. 

Note: in ACS, we do not see this issue occur -- it is only happening in IC3/GCC orgs. Issue happens with webchat version 4.15.4. Issue was not seen with webchat version 4.14.1.

### Do you see any errors in console log?

```js
This error shows up when the timestamp is not present as part of the message:
LiveChatWidgetLibs.min.js:332 TypeError: Cannot set properties of undefined (setting 'innerText')
    at LiveChatWidgetScripts.min.js:34:3431
    at Qb (LiveChatWidgetLibs.min.js:333:11)
    at si (LiveChatWidgetLibs.min.js:346:467)
    at Q (LiveChatWidgetLibs.min.js:191:262)
    at ta (LiveChatWidgetLibs.min.js:192:378)
    at e.port1.onmessage (LiveChatWidgetLibs.min.js:204:238)
```

### How to reproduce the issue?

1. Navigate to https://kevinlinclientdev.blob.core.windows.net/htmls/lcw-gcc-no-chatadaptershim.html
2. Load the widget
3. Type in the send box anything, then hit send.
4. Continue doing this for a string of messages to see the intermittent timestamp/delivery status regression behavior.

### What do you expect?

Timestamp and delivery status should show up below the message in the UI.

### What actually happened?

Timestamp and delivery status sometimes does not show up below the message in the UI.

### Do you have any screenshots or recordings to repro the issue?

Timestamp / delivery status does not show up:
<img width="546" alt="image" src="https://user-images.githubusercontent.com/13504205/213540028-328a35b2-f9c0-4f6c-af88-eb1ac1db1e48.png">

Timestamp / delivery status shows up:
<img width="530" alt="image" src="https://user-images.githubusercontent.com/13504205/213540057-55ffad8e-dc41-4c5a-b3a1-567624276c3e.png">

**Comment by stevkan** [comment]
@kevinlin98z, thank you for your patience while we started investigating this.

@ramfattah, I was unable to repro this is a stand alone Web Chat environment. Haven't tested via D365 nor do I have a GCC account to test with.

**Comment by ramfattah** [comment]
Thanks @kevinlin98z, I'm investigating.

**Comment by ramfattah** [comment]
@kevinlin98z, 

To clarify, are you able to repro this behavior in Azure Bot "Test in Web Chat"? 
![image](https://user-images.githubusercontent.com/38049078/217393491-49c0b858-18e1-434f-90c1-659e5aae83c9.png)

**Comment by ramfattah** [comment]
Closing due to inactivity. @kevinlin98z, please re-open if needed.
