### ISSUE TITLE
Using text to speech via webSpeechPonyfillFactory fails with 403 error

### ISSUE THREAD

**Issue by ricgreenwood** [microsoft/BotFramework-WebChat#4630]
### Is it an issue related to Adaptive Cards?

No

### Is this an accessibility issue?

No

### What version of Web Chat are you using?

Latest production

### Which distribution are you using Web Chat from?

Bundle (webchat.js)

### Which hosting environment does this issue primarily affect?

Web apps

### Which browsers and platforms do the issue happened?

Browser: Chrome (latest), Browser: Firefox (latest), Browser: Safari (latest), Platform: macOS

### Which area does this issue affect?

Speech

### Please describe the bug

Hi there,

we're using the renderWebChat function in the following way:
```js
const webChatOptions = {
directLine: createDirectLine({
secret: CONFIG.secret
}),
styleOptions: styleOptions(),
store: WEBCHAT_STORE,
userID: CONFIG.userID,
username: CONFIG.username || 'Web Chat User',
locale: CONFIG.locale || 'en-US',
webSpeechPonyfillFactory: null
}

if (CONFIG.speech.enable) {
    webChatOptions.webSpeechPonyfillFactory = await createCognitiveServicesSpeechServicesPonyfillFactory({
        credentials: {
            region: 'uksouth',
            subscriptionKey: OUR_RESOURCE_KEY
        }
    })
}

renderWebChat(webChatOptions, CONFIG.$chatElem)
```

This works with an older Speech service resource we created in November 2020 but fails to work with a newer resource of the same type that we created in March of 2022.

I can verify that both of the resources work correctly using the sample code at: https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/javascript/browser/text-to-speech

### Do you see any errors in console log?

```js
webchat.js:2          POST https://uksouth.tts.speech.microsoft.com/cognitiveservices/v1 403
(anonymous) @ webchat.js:2
p @ webchat.js:2
(anonymous) @ webchat.js:2
(anonymous) @ webchat.js:2
t @ webchat.js:2
s @ webchat.js:2
Promise.then (async)
t @ webchat.js:2
s @ webchat.js:2
(anonymous) @ webchat.js:2
(anonymous) @ webchat.js:2
y @ webchat.js:2
t.default @ webchat.js:2
value @ webchat.js:2
value @ webchat.js:2
(anonymous) @ webchat.js:2
l @ webchat.js:2
(anonymous) @ webchat.js:2
(anonymous) @ webchat.js:2
t @ webchat.js:2
s @ webchat.js:2
(anonymous) @ webchat.js:2
(anonymous) @ webchat.js:2
p @ webchat.js:2
f @ webchat.js:2
(anonymous) @ webchat.js:2
l @ webchat.js:2
(anonymous) @ webchat.js:2
(anonymous) @ webchat.js:2
t @ webchat.js:2
s @ webchat.js:2
(anonymous) @ webchat.js:2
(anonymous) @ webchat.js:2
value @ webchat.js:2
(anonymous) @ webchat.js:2
l @ webchat.js:2
(anonymous) @ webchat.js:2
(anonymous) @ webchat.js:2
l @ webchat.js:2
O @ webchat.js:2
(anonymous) @ webchat.js:2
(anonymous) @ webchat.js:2
t @ webchat.js:2
s @ webchat.js:2
(anonymous) @ webchat.js:2
(anonymous) @ webchat.js:2
(anonymous) @ webchat.js:2
(anonymous) @ webchat.js:2
(anonymous) @ webchat.js:2
(anonymous) @ webchat.js:2
ia @ webchat.js:2
La @ webchat.js:2
f @ webchat.js:2
d @ webchat.js:2
B.port1.onmessage @ webchat.js:2
webchat.js:2 synthesis-failed
(anonymous) @ webchat.js:2
l @ webchat.js:2
(anonymous) @ webchat.js:2
(anonymous) @ webchat.js:2
l @ webchat.js:2
O @ webchat.js:2
(anonymous) @ webchat.js:2
(anonymous) @ webchat.js:2
t @ webchat.js:2
u @ webchat.js:2
Promise.then (async)
t @ webchat.js:2
s @ webchat.js:2
(anonymous) @ webchat.js:2
(anonymous) @ webchat.js:2
(anonymous) @ webchat.js:2
(anonymous) @ webchat.js:2
(anonymous) @ webchat.js:2
(anonymous) @ webchat.js:2
ia @ webchat.js:2
La @ webchat.js:2
f @ webchat.js:2
d @ webchat.js:2
B.port1.onmessage @ webchat.js:2
webchat.js:2 Uncaught (in promise) Error: web-speech-cognitive-services: Failed to syntheis speech, server returned 403
    at webchat.js:2:2029194
    at p (webchat.js:2:3456555)
    at Generator._invoke (webchat.js:2:3456308)
    at Generator.next (webchat.js:2:3456918)
    at t (webchat.js:2:3448759)
    at s (webchat.js:2:3448970)
(anonymous) @ webchat.js:2
p @ webchat.js:2
(anonymous) @ webchat.js:2
(anonymous) @ webchat.js:2
t @ webchat.js:2
s @ webchat.js:2
Promise.catch (async)
value @ webchat.js:2
value @ webchat.js:2
(anonymous) @ webchat.js:2
l @ webchat.js:2
(anonymous) @ webchat.js:2
(anonymous) @ webchat.js:2
t @ webchat.js:2
s @ webchat.js:2
(anonymous) @ webchat.js:2
(anonymous) @ webchat.js:2
p @ webchat.js:2
f @ webchat.js:2
(anonymous) @ webchat.js:2
l @ webchat.js:2
(anonymous) @ webchat.js:2
(anonymous) @ webchat.js:2
t @ webchat.js:2
s @ webchat.js:2
(anonymous) @ webchat.js:2
(anonymous) @ webchat.js:2
value @ webchat.js:2
(anonymous) @ webchat.js:2
l @ webchat.js:2
(anonymous) @ webchat.js:2
(anonymous) @ webchat.js:2
l @ webchat.js:2
O @ webchat.js:2
(anonymous) @ webchat.js:2
(anonymous) @ webchat.js:2
t @ webchat.js:2
s @ webchat.js:2
(anonymous) @ webchat.js:2
(anonymous) @ webchat.js:2
(anonymous) @ webchat.js:2
(anonymous) @ webchat.js:2
(anonymous) @ webchat.js:2
(anonymous) @ webchat.js:2
ia @ webchat.js:2
La @ webchat.js:2
f @ webchat.js:2
d @ webchat.js:2
B.port1.onmessage @ webchat.js:2
webchat.js:2 Uncaught (in promise) Error: web-speech-cognitive-services: Failed to syntheis speech, server returned 403
    at webchat.js:2:2029194
    at p (webchat.js:2:3456555)
    at Generator._invoke (webchat.js:2:3456308)
    at Generator.next (webchat.js:2:3456918)
    at t (webchat.js:2:3448759)
    at s (webchat.js:2:3448970)
```

### How to reproduce the issue?

1. Navigate to ...
2. Click on ...
3. Type "..." in the send box

### What do you expect?

With the old resource the bot speaks to the user.

### What actually happened?

The bot doesn't speak to the user when using the new resource

**Comment by ramfattah** [comment]
Thanks @ricgreenwood for reporting this issue. We are investigating.

**Comment by ramfattah** [comment]
Hi @ricgreenwood, 

I was not able to reproduce this issue. Tested with webchat sample [b.cognitive-speech-services-js](https://github.com/microsoft/BotFramework-WebChat/tree/3011d9760c1be3dd9380316236d93b80178569fd/samples/03.speech/b.cognitive-speech-services-js).


https://user-images.githubusercontent.com/38049078/217381445-f4146a98-29df-414b-93d2-84ff35a73a76.mp4

<br/>

WebChat:
```html

<!DOCTYPE html>
<html lang="en-US">
  <head>
    <title>Web Chat: Cognitive Services Speech Services using JavaScript</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Cognitive Services Speech Services adapter is only available in full bundle -->
    <!--
      This CDN points to the latest official release of Web Chat. If you need to test against Web Chat's latest bits, please refer to using Web Chat's latest bits:
      https://github.com/microsoft/BotFramework-WebChat#how-to-test-with-web-chats-latest-bits
    -->
    <script crossorigin="anonymous" src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js"></script>
    <style>
      html,
      body {
        height: 100%;
      }

      body {
        margin: 0;
      }

      #webchat {
        height: 100%;
        width: 100%;
      }
    </style>
  </head>
  <body>
    <div id="webchat" role="main"></div>
    <script>
      (async function () {
        // Your client code must provide either a secret or a token to talk to your bot.
        // Tokens are more secure. To learn about the differences between secrets and tokens.
        // and to understand the risks associated with using secrets, visit https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-authentication?view=azure-bot-service-4.0
        const res = await fetch('https://directline.botframework.com/v3/directline/tokens/generate', {
          headers: {
            authorization: `Bearer <<directLine-secret>>`,
            'Content-Type': 'application/json'
          },
          method: 'POST',
        });
        const {token}  = await res.json();

        console.log("token ", token);

        // Create the ponyfill factory function, which can be called to create a concrete implementation of the ponyfill.
        const webSpeechPonyfillFactory = await window.WebChat.createCognitiveServicesSpeechServicesPonyfillFactory({
          // We are passing the Promise function to the "credentials" field.
          // This function will be called every time the token is being used.
          credentials: {
            region: 'westus2',
            subscriptionKey: "<<cognitive-speech-service-key>>"
          }
        });

        const webChatOptions = {
          directLine: window.WebChat.createDirectLine({ token }),
          webSpeechPonyfillFactory
        }

        // Pass a Web Speech ponyfill factory to renderWebChat.
        // You can also use your own speech engine given it is compliant to W3C Web Speech API: https://w3c.github.io/speech-api/.
        // For implementor, look at createBrowserWebSpeechPonyfill.js for details.
        window.WebChat.renderWebChat(webChatOptions, document.getElementById('webchat'));

        document.querySelector('#webchat > *').focus();
      })().catch(err => console.error(err));
    </script>
  </body>
</html>


```


@ricgreenwood, are you able to share your reproducible webchat .zip project with us so we can test it in our environment?

**Comment by ricgreenwood** [comment]
Hi Ram,

I’ve modified your test page (see below). I’ve then tried to replace the <<SPEECH KEY>> with the key from the old resource and the new resource. The old resource works when I press the microphone button. The new resource doesn’t. I’ve attached a screen shot of the errors produced. Hope this helps clarify the issue.

Regards,

Richard

<!DOCTYPE html>
<html lang="en-US">
  <head>
    <title>Web Chat: Cognitive Services Speech Services using JavaScript</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    
    <script crossorigin="anonymous" src=https://cdn.botframework.com/botframework-webchat/latest/webchat.js></script>
    <style>
      html,
      body {
        height: 100%;
      }

      body {
        margin: 0;
      }

      #webchat {
        height: 100%;
        width: 100%;
      }
    </style>
  </head>
  <body>
    <div id="webchat" role="main"></div>
    <script>
      (async function () {
        // Your client code must provide either a secret or a token to talk to your bot.
        // Tokens are more secure. To learn about the differences between secrets and tokens.
        // and to understand the risks associated with using secrets, visit https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-authentication?view=azure-bot-service-4.0
        // const res = await fetch('https://directline.botframework.com/v3/directline/tokens/generate', {
        //   headers: {
        //     authorization: `Bearer <<directLine-secret>>`,
        //     'Content-Type': 'application/json'
        //   },
        //   method: 'POST',
        // });
        // const {token}  = await res.json();

        // console.log("token ", token);

        // Create the ponyfill factory function, which can be called to create a concrete implementation of the ponyfill.
        const webSpeechPonyfillFactory = await window.WebChat.createCognitiveServicesSpeechServicesPonyfillFactory({
          // We are passing the Promise function to the "credentials" field.
          // This function will be called every time the token is being used.
          credentials: {
            region: 'uksouth',
            subscriptionKey: "<<SPEECH KEY>>"
          }
        });

        const webChatOptions = {
          // directLine: window.WebChat.createDirectLine({ token }),
          directLine: window.WebChat.createDirectLine({ secret: "<<SECRET>>" }),
          webSpeechPonyfillFactory
        }

        // Pass a Web Speech ponyfill factory to renderWebChat.
        // You can also use your own speech engine given it is compliant to W3C Web Speech API: https://w3c.github.io/speech-api/.
        // For implementor, look at createBrowserWebSpeechPonyfill.js for details.
        window.WebChat.renderWebChat(webChatOptions, document.getElementById('webchat'));

        document.querySelector('#webchat > *').focus();
      })().catch(err => console.error(err));
    </script>
  </body>
</html>


Richard Greenwood, Senior Educational Technology Developer
LTT Team, IET

From: Ram Fattah ***@***.***>
Date: Tuesday, 7 February 2023 at 22:40
To: microsoft/BotFramework-WebChat ***@***.***>
Cc: Richard.Greenwood ***@***.***>, Mention ***@***.***>
Subject: Re: [microsoft/BotFramework-WebChat] Using text to speech via webSpeechPonyfillFactory fails with 403 error (Issue #4630)

CAUTION: This mail comes from outside the University. Please consider this before opening attachments, clicking links, or acting on the content.

Hi @ricgreenwood<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fricgreenwood&data=05%7C01%7Crichard.greenwood%40open.ac.uk%7C3aebd7ea79c4402fb12108db095c47f7%7C0e2ed45596af4100bed3a8e5fd981685%7C0%7C0%7C638114064169199016%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hvBcIGV4dO8qCdY39JctxdwWbRMKYhx9GelXPuzaeOY%3D&reserved=0>,

I was not able to reproduce this issue. Tested with webchat sample b.cognitive-speech-services-js<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FBotFramework-WebChat%2Ftree%2F3011d9760c1be3dd9380316236d93b80178569fd%2Fsamples%2F03.speech%2Fb.cognitive-speech-services-js&data=05%7C01%7Crichard.greenwood%40open.ac.uk%7C3aebd7ea79c4402fb12108db095c47f7%7C0e2ed45596af4100bed3a8e5fd981685%7C0%7C0%7C638114064169199016%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=AAaFGWWWeS4DDoYew0phDxlfRvb4A0nZurR00ZeFc%2BU%3D&reserved=0>.

https://user-images.githubusercontent.com/38049078/217381445-f4146a98-29df-414b-93d2-84ff35a73a76.mp4<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F38049078%2F217381445-f4146a98-29df-414b-93d2-84ff35a73a76.mp4&data=05%7C01%7Crichard.greenwood%40open.ac.uk%7C3aebd7ea79c4402fb12108db095c47f7%7C0e2ed45596af4100bed3a8e5fd981685%7C0%7C0%7C638114064169199016%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=CelXtqwy2faa9IrOvDvuuQxZiC2EYSs3s7sGOzypoX4%3D&reserved=0>


WebChat:

<!DOCTYPE html>

<html lang="en-US">

  <head>

    <title>Web Chat: Cognitive Services Speech Services using JavaScript</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    

    

    <script crossorigin="anonymous" src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js"></script>

    <style>

      html,

      body {

        height: 100%;

      }



      body {

        margin: 0;

      }



      #webchat {

        height: 100%;

        width: 100%;

      }

    </style>

  </head>

  <body>

    <div id="webchat" role="main"></div>

    <script>

      (async function () {

        // Your client code must provide either a secret or a token to talk to your bot.

        // Tokens are more secure. To learn about the differences between secrets and tokens.

        // and to understand the risks associated with using secrets, visit https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-authentication?view=azure-bot-service-4.0

        const res = await fetch('https://directline.botframework.com/v3/directline/tokens/generate', {

          headers: {

            authorization: `Bearer <<directLine-secret>>`,

            'Content-Type': 'application/json'

          },

          method: 'POST',

        });

        const {token}  = await res.json();



        console.log("token ", token);



        // Create the ponyfill factory function, which can be called to create a concrete implementation of the ponyfill.

        const webSpeechPonyfillFactory = await window.WebChat.createCognitiveServicesSpeechServicesPonyfillFactory({

          // We are passing the Promise function to the "credentials" field.

          // This function will be called every time the token is being used.

          credentials: {

            region: 'westus2',

            subscriptionKey: "<<cognitive-speech-service-key>>"

          }

        });



        const webChatOptions = {

          directLine: window.WebChat.createDirectLine({ token }),

          webSpeechPonyfillFactory

        }



        // Pass a Web Speech ponyfill factory to renderWebChat.

        // You can also use your own speech engine given it is compliant to W3C Web Speech API: https://w3c.github.io/speech-api/.

        // For implementor, look at createBrowserWebSpeechPonyfill.js for details.

        window.WebChat.renderWebChat(webChatOptions, document.getElementById('webchat'));



        document.querySelector('#webchat > *').focus();

      })().catch(err => console.error(err));

    </script>

  </body>

</html>

@ricgreenwood<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fricgreenwood&data=05%7C01%7Crichard.greenwood%40open.ac.uk%7C3aebd7ea79c4402fb12108db095c47f7%7C0e2ed45596af4100bed3a8e5fd981685%7C0%7C0%7C638114064169199016%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hvBcIGV4dO8qCdY39JctxdwWbRMKYhx9GelXPuzaeOY%3D&reserved=0>, are you able to share your reproducible webchat .zip project with us so we can test it in our environment?

**Comment by ramfattah** [comment]
Thanks for the update @ricgreenwood, investigating further.

**Comment by ramfattah** [comment]
Hi @ricgreenwood,

I tried with UK South region speech resource and I'm not able to reproduce this issue.

Are you able to create and test with a new speech service resource to see if this error persists?

**Comment by ramfattah** [comment]
Closing due to inactivity.

@ricgreenwood, please re-open if needed. Thanks.
