### ISSUE TITLE
"scrollToEnd is not a function" TypeError when using connectSendTextBox 

### ISSUE THREAD

**Issue by feilindsay** [microsoft/BotFramework-WebChat#4868]
### Is it an issue related to Adaptive Cards?

No

### Is this an accessibility issue?

No

### What version of Web Chat are you using?

Latest production

### Which distribution are you using Web Chat from?

NPM

### Which hosting environment does this issue primarily affect?

Web apps

### Which browsers and platforms do the issue happened?

Browser: Chrome (latest)

### Which area does this issue affect?

Send box

### Please describe the bug

I'm using the connectSendTextBox to use WebChat's functionality on my own UI. However, when I press "Enter" in my text box, this error shows up in my console
<img width="466" alt="Screenshot 2023-09-20 154129" src="https://github.com/microsoft/BotFramework-WebChat/assets/30439766/2119cf51-d05b-4f3b-970d-0a4fb2050e62">

### Do you see any errors in console log?

```js
TextBox.tsx:49 Uncaught TypeError: scrollToEnd is not a function
    at onKeyPress (TextBox.tsx:49:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:1)
    at executeDispatch (react-dom.development.js:9041:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9073:1)
    at processDispatchQueue (react-dom.development.js:9086:1)
    at dispatchEventsForPlugins (react-dom.development.js:9097:1)
    at react-dom.development.js:9288:1
    at batchedUpdates$1 (react-dom.development.js:26140:1)
    at batchedUpdates (react-dom.development.js:3991:1)
    at dispatchEventForPluginEventSystem (react-dom.development.js:9287:1)
    at dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay (react-dom.development.js:6465:1)
    at dispatchEvent (react-dom.development.js:6457:1)
    at dispatchDiscreteEvent (react-dom.development.js:6430:1)
```

### How to reproduce the issue?

1. In a React web app, use `connectSendTextBox` and attach the selectors to your input UI.
    ex: `Components.connectSendTextBox()(({ ...selectors }) => <input {...selectors} />)`
2. Put this component in your ChatBot Composer
3. Run the web app in browser
4. Type a message in the input element and then press "Enter"

### What do you expect?

The message is sent and cleared from the text box. 

### What actually happened?

The message is not sent, the text box still contains the text, and I can no longer interact with the chat bot.

### Do you have any screenshots or recordings to repro the issue?

https://github.com/microsoft/BotFramework-WebChat/assets/30439766/5b3ea5a6-e216-4e05-a592-fe9264f4cdff

**Comment by compulim** [comment]
Sorry, all the `connectXXX` HOC functions are deprecated in favor of hooks. Please use our [hooks](https://github.com/microsoft/BotFramework-WebChat/blob/main/docs/HOOKS.md) for accessing those `selectors`.
