### ISSUE TITLE
Missing channelData on (GET .../activities) results, and Setting it to createStore({activities},...) Throws error

### ISSUE THREAD

**Issue by RamonDonadeu** [microsoft/BotFramework-WebChat#4973]
### Is it an issue related to Adaptive Cards?

No

### Is this an accessibility issue?

No

### What version of Web Chat are you using?

Unrelated

### Which distribution are you using Web Chat from?

Unrelated

### Which hosting environment does this issue primarily affect?

Web apps

### Which browsers and platforms do the issue happened?

Browser: Chrome (latest)

### Which area does this issue affect?

Chat history

### Please describe the bug

I'm trying to implement the webchat into a vue project. I'm storing conversation Id in cookies and when loading the page I retrieve the Id, and call
https://directline.botframework.com/v3/directline/conversations/{conversationId}/activities

to retrieve the sent messages in the past.

Then i'm setting them into 

```
const store = window.WebChat.createStore(
        {
          activities
        },...
```
 
So they can be viewed by the user, but it throws an error. ( Specified in 'Do you see any errors in console log?' )

I compared the activities object with the activities stored in the store if no activities ara passed and it's missing:
```
channelData: {
  'webchat:sequence-id': 1701695998289
}
```
on each message.

### Do you see any errors in console log?

```js
webchat.js:2 TypeError: Cannot read properties of undefined (reading 'has')
    at webchat.js:2:2288754
    at Object.useMemo (webchat.js:2:3136213)
    at useMemo (webchat.js:2:3196895)
    at y (webchat.js:2:2288012)
    at Qo (webchat.js:2:3132665)
    at webchat.js:2:3166054
    at Ka (webchat.js:2:3170044)
    at $a (webchat.js:2:3170426)
    at ks (webchat.js:2:3177452)
    at xs (webchat.js:2:3176832)
da @ webchat.js:2
Aa.i.componentDidCatch.r.callback @ webchat.js:2
ia @ webchat.js:2
oa @ webchat.js:2
Ya @ webchat.js:2
Wa @ webchat.js:2
(anonymous) @ webchat.js:2
t.unstable_runWithPriority @ webchat.js:2
Ds @ webchat.js:2
ks @ webchat.js:2
xs @ webchat.js:2
Is @ webchat.js:2
ts @ webchat.js:2
Us @ webchat.js:2
Vs @ webchat.js:2
Gs.render @ webchat.js:2
(anonymous) @ webchat.js:2
Bs @ webchat.js:2
qs @ webchat.js:2
render @ webchat.js:2
t.default @ webchat.js:2
webChatScript.onload @ WebChat.vue:224
load (async)
(anonymous) @ WebChat.vue:75
(anonymous) @ runtime-core.esm-bundler.js:2675
callWithErrorHandling @ runtime-core.esm-bundler.js:158
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:166
hook.__weh.hook.__weh @ runtime-core.esm-bundler.js:2655
flushPostFlushCbs @ runtime-core.esm-bundler.js:325
flushJobs @ runtime-core.esm-bundler.js:363
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:270
queueJob @ runtime-core.esm-bundler.js:264
reload @ runtime-core.esm-bundler.js:464
(anonymous) @ runtime-core.esm-bundler.js:494
(anonymous) @ WebChat.vue?t=1701698707137:311
(anonymous) @ client.ts:435
(anonymous) @ client.ts:351
(anonymous) @ client.ts:206
queueUpdate @ client.ts:206
await in queueUpdate (async)
(anonymous) @ client.ts:74
handleMessage @ client.ts:72
(anonymous) @ client.ts:45

botframework-webchat: Uncaught exception {error: TypeError: Cannot read properties of undefined (reading 'has')
    at https://cdn.botframework.com/…}

```

### How to reproduce the issue?

1.- Create a new conversation
2.- Write some messages
3.- Get the conversationId
4.- Call 'https://directline.botframework.com/v3/directline/conversations/' + conversationId + '/activities
5.- Get activities and set them into createStore
```
 const store = window.WebChat.createStore(
        {
          activities
        },
        ({ dispatch }) =>
          (next) =>
            (action) => {
             
              return next(action)
            }
      )
```
6.- Reload the page so it creates a webchat with set activities and it throws an error ( at least for me )

### What do you expect?

The recieved activities to be rendered in the webchat

### What actually happened?

Activities are not displayed due an error

### Additional context

I'll give you mi activities so you can skip 4 steps to reproduce:
```

const activities = [
        {
          type: 'message',
          id: 'Gii1iZbkiIOJHMv15obBic-fr|0000000',
          timestamp: '2023-12-04T14:01:54.2827331Z',
          localTimestamp: '2023-12-04T15:01:54.126+01:00',
          localTimezone: 'Europe/Madrid',
          serviceUrl: 'https://directline.botframework.com/',
          channelId: 'webchat',
          from: {
            id: 'YOUR_USER_ID',
            name: 'sergiy-test',
            role: 'user'
          },
          conversation: {
            id: 'Gii1iZbkiIOJHMv15obBic-fr'
          },
          textFormat: 'plain',
          locale: 'es',
          text: 'hola',
          attachments: [],
          entities: [
            {
              type: 'ClientCapabilities',
              requiresBotState: true,
              supportsListening: true,
              supportsTts: true
            }
          ],
          channelData: {
            clientActivityID: 'k0tz585kfil',
            
          }
        },
        {
          type: 'message',
          id: 'Gii1iZbkiIOJHMv15obBic-fr|0000001',
          timestamp: '2023-12-04T14:01:54.9070388Z',
          localTimestamp: '2023-12-04T15:01:54.812+01:00',
          localTimezone: 'Europe/Madrid',
          serviceUrl: 'https://directline.botframework.com/',
          channelId: 'webchat',
          from: {
            id: 'YOUR_USER_ID',
            name: 'sergiy-test',
            role: 'user'
          },
          conversation: {
            id: 'Gii1iZbkiIOJHMv15obBic-fr'
          },
          textFormat: 'plain',
          locale: 'es',
          text: 'hola',
          attachments: [],
          channelData: {
            clientActivityID: 'csv02ro4e25',
           
          }
        },
        {
          type: 'message',
          id: 'Gii1iZbkiIOJHMv15obBic-fr|0000002',
          timestamp: '2023-12-04T14:01:55.2415979Z',
          channelId: 'webchat',
          from: {
            id: 'test-ramon-bot',
            name: 'test-ramon-bot'
          },
          conversation: {
            id: 'Gii1iZbkiIOJHMv15obBic-fr'
          },
          locale: 'es',
          text: 'alguna respuesta de texto',
          inputHint: 'acceptingInput',
          attachments: [],
          entities: [],
          replyToId: 'Gii1iZbkiIOJHMv15obBic-fr|0000000'
        },
        {
          type: 'message',
          id: 'Gii1iZbkiIOJHMv15obBic-fr|0000003',
          timestamp: '2023-12-04T14:01:56.017105Z',
          channelId: 'webchat',
          from: {
            id: 'test-ramon-bot',
            name: 'test-ramon-bot'
          },
          conversation: {
            id: 'Gii1iZbkiIOJHMv15obBic-fr'
          },
          locale: 'es',
          text: 'alguna respuesta de texto',
          inputHint: 'acceptingInput',
          attachments: [],
          entities: [],
          replyToId: 'Gii1iZbkiIOJHMv15obBic-fr|0000001'
        }
      ]
```

**Comment by RamonDonadeu** [comment]
I have an automatic message that displays a card. That works always, i can restart the chat 50 times and there will be 50 cards, but arround the 20th message, if i write something. the next time i reload the chat it throws the error.

I got the last 4 messages where the message written by me is:

```

    {
        "type": "message",
        "id": "DyO0QkdgqHg49WD7sw3RVo-fr|0000029",
        "timestamp": "2023-12-04T16:13:03.6784072Z",
        "channelId": "webchat",
        "from": {
            "id": "test-ramon-bot",
            "name": "test-ramon-bot"
        },
        "conversation": {
            "id": "DyO0QkdgqHg49WD7sw3RVo-fr"
        },
        "locale": "es",
        "text": "Ramón, Bienvenido/a al Bot de Soporte de.",
        "inputHint": "acceptingInput",
        "attachments": [],
        "entities": [],
        "replyToId": "DyO0QkdgqHg49WD7sw3RVo-fr|0000028",
        "channelData": {}
    },
    {
        "type": "message",
        "id": "DyO0QkdgqHg49WD7sw3RVo-fr|0000030",
        "timestamp": "2023-12-04T16:13:03.7537216Z",
        "channelId": "webchat",
        "from": {
            "id": "test-ramon-bot",
            "name": "test-ramon-bot"
        },
        "conversation": {
            "id": "DyO0QkdgqHg49WD7sw3RVo-fr"
        },
        "attachmentLayout": "list",
        "locale": "es",
        "inputHint": "acceptingInput",
        "attachments": [
            {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                    "type": "AdaptiveCard",
                    "version": "1.0",
                    "backgroundImage": "",
                    "body": [
                        {
                            "type": "TextBlock",
                            "text": "Selecciona una opción:",
                            "weight": "bolder",
                            "size": "medium"
                        }
                    ],
                    "actions": [
                        {
                            "type": "Action.Submit",
                            "title": "Iniciar conversación con un departamento",
                            "data": {
                                "action": "startConversation"
                            }
                        },
                        {
                            "type": "Action.Submit",
                            "title": "Enviar un formulario",
                            "data": {
                                "action": "startForm"
                            }
                        }
                    ]
                }
            }
        ],
        "entities": [],
        "replyToId": "DyO0QkdgqHg49WD7sw3RVo-fr|0000028",
        "channelData": {}
    },
    {
        "type": "message",
        "id": "DyO0QkdgqHg49WD7sw3RVo-fr|0000031",
        "timestamp": "2023-12-04T16:13:08.6588667Z",
        "localTimestamp": "2023-12-04T17:13:08.536+01:00",
        "localTimezone": "Europe/Madrid",
        "serviceUrl": "https://directline.botframework.com/",
        "channelId": "webchat",
        "from": {
            "id": "YOUR_USER_ID",
            "name": "sergiy-test",
            "role": "user"
        },
        "conversation": {
            "id": "DyO0QkdgqHg49WD7sw3RVo-fr"
        },
        "textFormat": "plain",
        "locale": "es",
        "text": "hola",
        "attachments": [],
        "channelData": {}
    },
    {
        "type": "message",
        "id": "DyO0QkdgqHg49WD7sw3RVo-fr|0000032",
        "timestamp": "2023-12-04T16:13:08.9682547Z",
        "channelId": "webchat",
        "from": {
            "id": "test-ramon-bot",
            "name": "test-ramon-bot"
        },
        "conversation": {
            "id": "DyO0QkdgqHg49WD7sw3RVo-fr"
        },
        "locale": "es",
        "text": "alguna respuesta de texto",
        "inputHint": "acceptingInput",
        "attachments": [],
        "entities": [],
        "replyToId": "DyO0QkdgqHg49WD7sw3RVo-fr|0000031",
        "channelData": {}
    }
]
```

and it says:

```
TypeError: Cannot read properties of undefined (reading 'has')
    at webchat.js:2:2288754
    at Object.useMemo (webchat.js:2:3136213)
    at useMemo (webchat.js:2:3196895)
    at y (webchat.js:2:2288012)
    at Qo (webchat.js:2:3132665)
    at webchat.js:2:3166054
    at Ka (webchat.js:2:3170044)
    at $a (webchat.js:2:3170426)
    at ks (webchat.js:2:3177452)
    at xs (webchat.js:2:3176832)
```

**Comment by RamonDonadeu** [comment]
UPDATE

After looking which messages throw an error I started looking for which key throws the error also.

```
const activities = [
        {
          type: 'message',
          id: '1px0sZT1bJHKtlOFQWHIo1-fr|0000003',
          timestamp: '2023-12-05T07:21:40.7720429Z',
          localTimestamp: '2023-12-05T08:11:40.485+01:00',
          localTimezone: 'Europe/Madrid',
          serviceUrl: 'https://directline.botframework.com/',
          channelId: 'webchat',
          from: {
            id: 'YOUR_USER_ID',
            name: 'sergiy-test',
            role: 'user'
          },
          conversation: {
            id: '1px0sZT1bJHKtlOFQWHIo1-fr'
          },
          textFormat: 'plain',
          locale: 'es',
          text: 'hola',
          attachments: [],
          channelData: {
            clientActivityID: '5r9btokkyma'
          }
        }
      ]
```

In this case if in localTimestamp I remove the +01:00 and set it to +00:00 it works, i can delete the entire line and it works too. 
If i delete channelData it stills throws error.
