### ISSUE TITLE
"conversation ended" error which leads to send failed error for user message

### ISSUE THREAD

**Issue by SanKumar0632** [microsoft/BotFramework-WebChat#4998]
### Is it an issue related to Adaptive Cards?

No

### Is this an accessibility issue?

No

### What version of Web Chat are you using?

Latest production

### Which distribution are you using Web Chat from?

NPM

### Which hosting environment does this issue primarily affect?

Web apps

### Which browsers and platforms do the issue happened?

Platform: iOS/iPadOS

### Which area does this issue affect?

Protocol or service

### What is the public URL for the website?

https://healo.infiheal.com/

### Please describe the bug

Inside Safari browser in IOS, when I open the keyboard I can see the "conversation ended" error using Xcode with Webinspect, then if I send a message it is not sent or arbitrarily gets sent and shows "Send Faliled Retry".
![WhatsApp Image 2023-12-31 at 01 35 35_aafa06f8](https://github.com/microsoft/BotFramework-WebChat/assets/122610382/072b0bc7-b767-4fa2-8a8c-2a122ef44b94)
![WhatsApp Image 2023-12-31 at 01 35 35_e374ef86](https://github.com/microsoft/BotFramework-WebChat/assets/122610382/b7a09b5b-ccf7-4c3c-8fe3-82d58945205c)

### Do you see any errors in console log?

```js
Uncaught Error: conversation ended
    at ./node_modules/botframework-directlinejs/lib/directLine.js (directLine.ts:435:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/botframework-webchat/lib/createDirectLine.js (createDirectLine.ts:1:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/botframework-webchat/lib/index-minimal.js (index-minimal.ts:24:1)
    at options.factory (react refresh:6:1)
```

### How to reproduce the issue?

1.go to the url https://healo.infiheal.com/ in an iphone 12
2.Scrolldown to see the type box and tap on it to type
3.See error in console

### What do you expect?

It should not give the uncaught error "conversation ended".

### What actually happened?

The error comes in console whenever I try to open the keyboard to type and message send fails
![WhatsApp Image 2023-12-30 at 23 19 37_0b8e5109](https://github.com/microsoft/BotFramework-WebChat/assets/122610382/58ec15fb-2924-4716-a390-f0463caae77f)

### Additional context

We are using the npm package botframework-webchat to integrate the bot ui in **react** frontend.

**Comment by Yokee-ss-hh** [comment]
I am facing the same issue. @SanKumar0632 Did you resolved the issue ? If YES, Can you update the solution in the comments.  
<img width="960" alt="2024-01-24_20h12_12" src="https://github.com/microsoft/BotFramework-WebChat/assets/82704862/4c074d28-06a4-45e6-9f23-1a8f10d4b8cf">
