### ISSUE TITLE
CommonJS 4.17.0 Issue - EJS botframework-webchat-api

### ISSUE THREAD

**Issue by shah-vtx** [microsoft/BotFramework-WebChat#5238]
### Is it an issue related to Adaptive Cards?

No

### Is this an accessibility issue?

No

### What version of Web Chat are you using?

Latest production

### Which distribution are you using Web Chat from?

NPM

### Which hosting environment does this issue primarily affect?

Web apps

### Which browsers and platforms do the issue happened?

Others or unrelated

### Which area does this issue affect?

Others or unrelated

### Which theme pack does this issue affect?

I did not test it on other theme packs

### Please describe the bug

<img width="519" alt="image" src="https://github.com/microsoft/BotFramework-WebChat/assets/119691659/6c1b1c2a-8b0b-46d0-bd93-8acdee31e4fe">

    
I'm using a TS project with webpack. It is using commonjs. 4.16.0 works perfectly fine but as soon as I switch to the latest 4.17.0, I get runtime errors in the console in the browser because it is trying to use .mjs files. I also saw this [PR](https://github.com/microsoft/BotFramework-WebChat/pull/5231) and thought it would fix it so I tried the latest main version: [4.17.1-main.20240708.c9247bf](https://www.npmjs.com/package/botframework-webchat-api/v/4.17.1-main.20240708.c9247bf).
    
    

### Do you see any errors in console log?

```js
botframework-webchat-api.mjs:1 Uncaught (in promise) TypeError: i is not a function
    at botframework-webchat-api.mjs:1:23790
    at chunk-4ZIUY4G5.mjs:1:182
    at ./node_modules/botframework-webchat-api/dist/botframework-webchat-api.mjs (botframework-webchat-api.mjs:139:43590)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/botframework-webchat-component/dist/botframework-webchat-component.mjs (botframework-webchat-component.internal.mjs:3:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/botframework-webchat/dist/chunk-EZUR2UAI.mjs (botframework-webchat.mjs:3:1)
    at __webpack_require__ (bootstrap:24:1)
```

### How to reproduce the issue?

As as you load it in the browser.

### What do you expect?

For the page to load and crash to not occur.

### What actually happened?

Crashes with console error

### Do you have any screenshots or recordings to repro the issue?

N/A

**Comment by OEvgeny** [comment]
We had some fixes related to Webpack, please try `4.18.0`

**Comment by shah-vtx** [comment]
I used 4.18.0 and still seeing the same issue.

**Comment by OEvgeny** [comment]
Looks like another regression with globalize.

The `i` refers to `Globalize._numberRound` where the `Globalize` is imported from `globalize/dist/globalize-runtime` as CJS module:
![image](https://github.com/user-attachments/assets/bbd0e9cc-febe-4ad1-898c-4b2c0f0b2221)

cc @compulim

**Comment by OEvgeny** [comment]
@shah-vtx could you share your webpack configuration and exact versions of webopack and plugins used?

**Comment by OEvgeny** [comment]
There is a known issue with Webpack v5 mentioned in changelog:
> ## [4.17.0] - 2024-05-06
>
> ### Known issues
>
> -  Web Chat is not loading with error `Uncaught TypeError: Super constructor null of anonymous class is not a constructor`
>   -  A [bug in webpack@>=5.84.1](https://github.com/webpack/webpack/issues/17711) is causing the issue. Please update to [`webpack@>=5.90.0`](https://npmjs.com/package/webpack/v/5.90.0)

Please make sure you're using the right version.

**Comment by shah-vtx** [comment]
I did an override in my package.json to webpack 5.90.0 and still the same runtime console error.

<img width="362" alt="image" src="https://github.com/user-attachments/assets/0aa2f010-38f3-440d-8411-f3dc5bd89b1b">

**Comment by OEvgeny** [comment]
Can't assist without further details on webpack configuration and used versions.
> @shah-vtx could you share your webpack configuration and exact versions of webopack and plugins used?

**Comment by light049** [comment]
I think I'm facing similar issue... Q_Q
I use CRA("react-scripts": "5.0.0") with craco(7.1.0) to help some customization

Although it seems successful when run dev service.
![Image](https://github.com/user-attachments/assets/02e5c934-1613-4987-9009-39eeec67275f)

But it gets failed.
![Image](https://github.com/user-attachments/assets/e4fbccba-95df-40dd-b372-1494e7c71c2b)

**Comment by OEvgeny** [comment]
From what I recall, CRA should use CJS, not ESM, so something is going on with the configuration. In the next nightly we'll have a slightly different build. It may affect some old configurations.

**Comment by light049** [comment]
> From what I recall, CRA should use CJS, not ESM, so something is going on with the configuration. In the next nightly we'll have a slightly different build. It may affect some old configurations.

Is there any update for this issue?
