### ISSUE TITLE
Uncaught exception in Speech re initialization

### ISSUE THREAD

**Issue by srijiths** [Microsoft/BotFramework-WebChat#654]
If we click on the Mic multiple times by mistake , there is an uncaught exception which is causing issues. Due to this issue , bot is getting in to a loop and never coming out with out a refresh page.

botchat.js:1426 Uncaught DOMException: Failed to execute 'start' on 'SpeechRecognition': recognition has already started.
    at BrowserSpeechRecognizer.startRecognizing (http://IP/sample_files/botchat.js:5348:29)
    at Function.SpeechRecognizer.startRecognizing (http://IP/sample_files/botchat.js:5253:39)
    at SafeSubscriber._next (http://IP/sample_files/botchat.js:17787:48)
    at SafeSubscriber.__tryOrSetError (http://IP/sample_files/botchat.js:1466:16)
    at SafeSubscriber.next (http://IP/sample_files/botchat.js:1406:27)
    at Subscriber._next (http://IP/sample_files/botchat.js:1344:26)
    at Subscriber.next (http://IP/sample_files/botchat.js:1308:18)
    at DoSubscriber._next (http://IP/sample_files/botchat.js:44464:24)
    at DoSubscriber.Subscriber.next (http://IP/sample_files/botchat.js:1308:18)
    at FilterSubscriber._next (http://IP/sample_files/botchat.js:16301:30)

**Comment by danmarshall** [comment]
@shahidkhuram - can you look into this?

**Comment by shahidkhuram** [comment]
I can repro the issue. From a quick look it appears that stopping a recognizer isn't a synchronous operation so attempting to stop & start in quick succession is leading to this exception. stop() doesn't return a promise. One solution would be to throttle/debounce the start listening operation. I tried that quickly and I appears to resolve the problem. I'll try to send out a PR in the next day or so.

**Comment by billba** [comment]
This is literally the sort of async nonsense that RxJS was designed to do!

**Comment by compulim** [comment]
Related to PR #657.

**Comment by compulim** [comment]
Fixed in #881.
